// 真实 UI：分组→跨层复制→单步撤销/重做→搜索/解组→多删撤销→保存重开。
import { expect, expectAbsent, proveProbe } from './_assert.mjs'
import { launchDirectorLab, openAddMenu, placeCharacter } from './_directorLab.mjs'

const lab = await launchDirectorLab({ name: 'j8-project-interactions' })
const { page, check } = lab
try {
  await placeCharacter(lab, 'female', -1, 0)
  await placeCharacter(lab, 'male', 1, 0)
  await lab.waitScene('s.objects.length === 2', '两个角色')
  const original = await lab.scene(), names = original.objects.map(item => item.name)
  await lab.outlinerRow(names[0]).click()
  await page.getByTestId('director-viewport').hover({ position: { x: 500, y: 450 } })
  await page.keyboard.press('4')
  const creationMode = page.locator('[data-nomi-director-creation-mode]')
  await expect(creationMode).toBeVisible()
  const drawingProof = await proveProbe(creationMode, '画笔创建模式已经进入')
  await page.keyboard.press('Escape')
  await expectAbsent(creationMode, { provenBy: drawingProof, message: 'Esc 后画笔创建模式持续退出' })
  check('Esc先取消画笔并保留选择', (await lab.outlinerRow(names[0]).getAttribute('class')).includes('bg-nomi-accent-soft'))
  await openAddMenu({ page }, '方块')
  await expect(creationMode).toBeVisible()
  const boxProof = await proveProbe(creationMode, '方块创建模式已经进入')
  await page.keyboard.press('Escape')
  await expectAbsent(creationMode, { provenBy: boxProof, message: 'Esc 后方块创建模式持续退出' })
  check('首次方块模式也能立即取消', true)
  // 画框开始本就清选择；重新建立选择，才有资格验证下一层 Esc 清选择。
  await lab.outlinerRow(names[0]).click()
  await expect(lab.outlinerRow(names[0])).toHaveClass(/bg-nomi-accent-soft/)
  await page.keyboard.press('Escape')
  await expect(lab.outlinerRow(names[0])).not.toHaveClass(/bg-nomi-accent-soft/)
  check('第二层Esc清除已建立的选择', true)
  await lab.outlinerRow(names[0]).click()
  await lab.outlinerRow(names[1]).click({ modifiers: ['Control'] })
  await page.getByTestId('director-selection-bar').getByRole('button', { name: '打组', exact: true }).click()
  await lab.waitScene("s.objects.some(o=>o.type==='group')", '打组')
  const grouped = await lab.scene(), group = grouped.objects.find(item => item.type === 'group')
  check('打组后两个角色都属于组', grouped.objects.filter(item => item.parentId === group.id).length === 2)
  await lab.outlinerRow(group.name).click({ button: 'right' })
  await page.getByRole('button', { name: '新建图层并复制', exact: true }).click()
  await lab.waitScene('p.scenes.length===2 && s.objects.length===3', '整组复制到新层')
  check('复制保留整组', true)
  await lab.snap('copied-group')
  await page.keyboard.press('Control+z')
  await lab.waitScene('p.scenes.length===1 && s.objects.length===3', '一次撤销整次新层复制')
  await page.keyboard.press('Control+Shift+z')
  await lab.waitScene('p.scenes.length===2 && s.objects.length===3', '重做整次复制')
  check('新建层和复制只占一次撤销', true)

  await lab.outlinerRow(group.name).locator('button').first().click()
  const search = page.getByTestId('director-outliner').locator('input[placeholder]')
  await search.fill(names[0])
  await expect(lab.outlinerRow(names[0])).toBeVisible()
  check('搜索能展开折叠组里的命中角色', true)
  await search.press('Escape')
  await lab.outlinerRow(group.name).click({ button: 'right' })
  await page.getByRole('button', { name: '解散组', exact: true }).click()
  await lab.waitScene("s.objects.length===2 && s.objects.every(o=>!o.parentId)", '右键解组')
  await lab.outlinerRow(names[0]).click()
  await lab.outlinerRow(names[1]).click({ modifiers: ['Control'] })
  const deleteProofs = await Promise.all(names.map(name => proveProbe(lab.outlinerRow(name), `删除前角色 ${name} 存在`)))
  await page.getByTestId('director-selection-bar').getByRole('button', { name: '删除', exact: true }).click()
  await lab.waitScene('s.objects.length===0', '批量删除')
  await Promise.all(names.map((name, index) => expectAbsent(lab.outlinerRow(name), { provenBy: deleteProofs[index], message: `批量删除后角色 ${name} 持续退出列表` })))
  await page.keyboard.press('Control+z')
  await lab.waitScene('s.objects.length===2', '单次撤销恢复全部删除')
  check('解组与批量删除撤销有效', true)
  await lab.snap('ungroup-delete-undo')

  const beforeReload = await lab.project()
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.getByTestId('director-pip')).toBeVisible()
  await lab.waitScene('p.scenes.length===2 && s.objects.length===2', '保存重开')
  const afterReload = await lab.project()
  check('保存重开完整保留工程', JSON.stringify(beforeReload) === JSON.stringify(afterReload))
  await lab.snap('saved-and-reopened')
} catch (error) {
  console.error(error)
  await lab.snap('failure')
  check(`旅程中断：${String(error.message || error).split('\n')[0]}`, false)
}
finally { await lab.finish() }
