import fs from 'node:fs'
import path from 'node:path'
import { launchNomiApp } from './_launchApp.mjs'
import { expect, expectAbsent, proveProbe } from './_assert.mjs'
import { stationTimeout } from './_station-budget.mjs'
import { COMPOSER_SKILL, SKILL_POPOVER } from './agent-runtime-walk-support.mjs'
const output = path.resolve('docs/design/verification/2026-09-09-skill-library')
fs.mkdirSync(output, { recursive: true })
const run = await launchNomiApp({ name: 'skill-library-cards', settleMs: 0,
  env: process.env.NOMI_SKILL_UI_DEV_URL ? { NOMI_RENDERER_URL: process.env.NOMI_SKILL_UI_DEV_URL, VITE_DEV_SERVER_URL: process.env.NOMI_SKILL_UI_DEV_URL } : {},
  initialLocalStorage: { 'nomi-color-scheme': 'light', 'nomi:splash:v1': 'seen', 'nomi:journey-tour:v1': 'seen', 'nomi:canvas-gesture-hint:v1': 'seen' },
})
async function expandGroups(host) {
  while (await host.locator('details:not([open]) > summary').count()) await host.locator('details:not([open]) > summary').first().click()
}
const page = run.win
page.setDefaultTimeout(stationTimeout({ operations: 2 }))
try {
  const window = await run.app.browserWindow(page)
  await window.evaluate(w => w.setBounds({ x: 0, y: 0, width: 1680, height: 980 }))
  await page.getByRole('button', { name: '新建空白项目', exact: false }).first().click()
  const skillButton = page.locator(COMPOSER_SKILL).first()
  await skillButton.click()
  const picker = page.locator(SKILL_POPOVER).first()
  await picker.getByRole('button', { name: '新建 · 管理', exact: false }).click()
  const gallery = page.locator('[data-skill-drop-zone]')
  await proveProbe(gallery.locator('[data-skill-card]'), '真实技能卡片已加载')
  await gallery.getByRole('radio', { name: '技能', exact: true }).click()
  await expect(gallery.getByRole('radio', { name: '技能', exact: true })).toHaveAttribute('aria-checked', 'true')
  await expandGroups(gallery)
  const multi = gallery.locator('[data-skill-card="skill:curated-multi-view"]')
  await multi.scrollIntoViewIfNeeded()
  await expect(multi.locator('img')).toBeVisible()
  await expect.poll(() => multi.locator('img').evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true)
  await page.screenshot({ path: path.join(output, '01-library.png') })
  await multi.click()
  const detail = page.locator('[data-skill-detail]')
  await expect(detail.getByRole('heading', { name: '多视图设定', exact: true })).toBeVisible()
  await expect(detail.getByRole('heading', { name: '配方', exact: true })).toBeVisible()
  await expect(detail).not.toContainText('metadata:')
  await page.screenshot({ path: path.join(output, '02-detail.png') })
  await detail.getByRole('button', { name: '引用到 Agent', exact: true }).click()
  await expect(page.locator('[data-v4-chip="skill"]').first()).toContainText('多视图设定')
  await page.locator(COMPOSER_SKILL).first().click()
  const selectedPicker = page.locator(SKILL_POPOVER).first()
  await expandGroups(selectedPicker)
  const promptProof = await proveProbe(selectedPicker.locator('[data-v4-command^="prompt:"]'), '全部分面显示提示词')
  const skillProof = await proveProbe(selectedPicker.locator('[data-v4-command^="skill:"]'), '全部分面显示技能')
  await selectedPicker.getByRole('button', { name: '技能', exact: true }).click()
  await expectAbsent(selectedPicker.locator('[data-v4-command^="prompt:"]'), { provenBy: promptProof })
  await selectedPicker.locator('[data-v4-control="skill-search"]').fill('多视图')
  await selectedPicker.locator('[data-v4-command="skill:curated-multi-view"]').hover()
  await expect(page.locator('[data-skill-hover="skill:curated-multi-view"]').first()).toBeVisible()
  await page.screenshot({ path: path.join(output, '03-composer-preview.png') })
  await page.keyboard.press('Escape')
  await page.locator(COMPOSER_SKILL).first().click()
  await selectedPicker.locator('[data-v4-control="skill-search"]').fill('')
  await selectedPicker.getByRole('button', { name: '效果', exact: true }).click()
  await expectAbsent(selectedPicker.locator('[data-v4-command^="skill:"]'), { provenBy: skillProof })
  await expandGroups(selectedPicker)
  await expect(selectedPicker.locator('[data-v4-command="prompt:effect-character-three-view"]')).toBeVisible()
  await selectedPicker.getByRole('button', { name: '新建 · 管理', exact: false }).click()
  await gallery.getByRole('radio', { name: '效果', exact: true }).click()
  await expect(gallery.getByRole('radio', { name: '效果', exact: true })).toHaveAttribute('aria-checked', 'true')
  await expandGroups(gallery)
  await gallery.locator('[data-skill-card="prompt:effect-character-three-view"]').click()
  await detail.getByRole('button', { name: '用到节点', exact: true }).click()
  await expect(page.locator('[data-node-effect-chips="filled"]')).toBeVisible()
  const editor = page.locator('.generation-canvas-v2-node__composer [contenteditable="true"]').first()
  await editor.fill('')
  await expect(page.locator('[data-node-effect-chips="empty"] [data-effect-chip]')).toHaveCount(4)
  const chipsProof = await proveProbe(page.locator('[data-effect-chip]'), '空节点四个常用效果')
  await page.screenshot({ path: path.join(output, '04-node-empty.png') })
  await page.locator('[data-effect-more]').click()
  await expect(page.getByTestId('node-effect-menu')).toBeVisible()
  const triggerRect = await page.locator('[data-effect-more]').boundingBox()
  const menuRect = await page.getByTestId('node-effect-menu').boundingBox()
  expect(Math.abs(menuRect.x - triggerRect.x), 'Effect menu must remain beside its viewport anchor').toBeLessThan(32)
  await page.keyboard.press('Escape')
  const composer = page.locator('.generation-canvas-v2-node__composer').first()
  await composer.evaluate(element => { element.style.translate = '37px 19px' })
  await page.locator('[data-effect-more]').click()
  await expect.poll(async () => {
    const trigger = await page.locator('[data-effect-more]').boundingBox()
    const menu = await page.getByTestId('node-effect-menu').boundingBox()
    return Math.abs(menu.x - trigger.x)
  }, { message: 'Additional transformed ancestry must not displace the menu anchor' }).toBeLessThan(32)
  await page.keyboard.press('Escape')
  await composer.evaluate(element => { element.style.translate = '' })
  await page.locator('[data-effect-more]').click()
  await page.screenshot({ path: path.join(output, '05-node-more.png') })
  await page.getByTestId('node-effect-menu').getByText('人物三视图', { exact: true }).click()
  await expect(editor).toContainText('三格人物等高')
  await expectAbsent(page.locator('[data-effect-chip]'), { provenBy: chipsProof })
  await page.screenshot({ path: path.join(output, '06-node-filled.png') })
  await page.getByRole('button', { name: '撤销', exact: true }).last().click()
  await expect(editor).toHaveText('')
  await expect(page.locator('[data-effect-chip]')).toHaveCount(4)
  fs.writeFileSync(path.join(output, 'journey.json'), JSON.stringify({ passed: true, paidCalls: 0, tasks: ['browse and reference skill', 'filter and preview picker', 'apply effect and undo'] }, null, 2) + '\n')
} catch (error) {
  console.error(error)
  await page.screenshot({ path: path.join(output, 'FAIL.png') }).catch(captureError => console.error(captureError))
  throw error
} finally { await run.close() }
