import React from 'react'
import { useTranslation } from 'react-i18next'
import { IconChevronDown, IconPaperclip, IconSend2, IconSquare } from '@tabler/icons-react'
import { cn } from '../../../utils/cn'
import { approvalPolicyForLabel, shouldSubmitComposer, useComposerHeight } from './agentPanelV4Logic'
import type { ComposerMode, PermissionLabel } from './agentPanelV4Types'

export function AgentPanelV4Composer({ panelHeight = 620, mode = 'idle', permission = '自动改', reference, initialText = '' }: { panelHeight?: number; mode?: ComposerMode; permission?: PermissionLabel; reference?: string; initialText?: string }): JSX.Element {
  const { t } = useTranslation()
  const [value, setValue] = React.useState(initialText)
  const lineCount = Math.max(1, value.split('\n').length)
  const height = useComposerHeight(panelHeight, mode, lineCount)
  const submit = () => setValue('')
  return <form className={cn('grid shrink-0 gap-1.5 overflow-hidden rounded-nomi border border-nomi-line bg-nomi-paper p-2', mode !== 'idle' && 'border-nomi-accent')} style={{ height, maxHeight: height }} onSubmit={(event) => { event.preventDefault(); submit() }} data-v4-block="composer" data-mode={mode} data-height={height} data-approval-mode={approvalPolicyForLabel(permission).mode} data-spend-policy={approvalPolicyForLabel(permission).spend}>{reference ? <div className="flex min-h-0 flex-wrap gap-1 overflow-hidden"><span className="inline-flex shrink-0 items-center gap-1 rounded-nomi-sm border border-nomi-line px-1.5 py-0.5 text-micro"><IconPaperclip size={12} />{t('agentPanelV4.attachment')}<span className="text-nomi-ink-40">×</span></span><span className="inline-flex shrink-0 items-center rounded-nomi-sm border border-nomi-accent bg-nomi-accent-soft px-1.5 py-0.5 text-micro text-nomi-accent">{t('agentPanelV4.skill')}</span></div> : null}<div className="flex min-h-0 items-end gap-2"><textarea value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (shouldSubmitComposer({ key: event.key, shiftKey: event.shiftKey, isComposing: event.nativeEvent.isComposing })) { event.preventDefault(); submit() } }} placeholder={t('agentPanelV4.placeholder')} aria-label={t('agentPanelV4.message')} className="min-h-0 min-w-0 flex-1 resize-none overflow-y-auto bg-transparent text-micro leading-relaxed outline-none" rows={1} /><button type={mode === 'running' ? 'button' : 'submit'} aria-label={mode === 'running' ? t('agentPanelV4.stop') : t('agentPanelV4.send')} className="grid size-7 shrink-0 place-items-center rounded-pill bg-nomi-ink text-nomi-paper">{mode === 'running' ? <IconSquare size={13} /> : <IconSend2 size={14} />}</button></div><div className="flex min-h-0 items-center gap-1 text-micro text-nomi-ink-60"><button type="button" className="grid size-6 shrink-0 place-items-center rounded-nomi-sm hover:bg-nomi-ink-05" aria-label={t('agentPanelV4.attach')}><IconPaperclip size={14} /></button><button type="button" className="inline-flex shrink-0 items-center gap-1 whitespace-nowrap rounded-nomi-sm px-1.5 py-1 hover:bg-nomi-ink-05">{t('agentPanelV4.model')} <IconChevronDown size={12} /></button><span className="h-4 w-px shrink-0 bg-nomi-line" /><button type="button" className="inline-flex shrink-0 items-center gap-1 whitespace-nowrap rounded-nomi-sm px-1.5 py-1 hover:bg-nomi-ink-05">{permission}<IconChevronDown size={12} /></button>{reference ? <span className="ml-auto max-w-[140px] truncate rounded-pill bg-nomi-accent-soft px-1.5 py-0.5 text-nomi-accent">{t('agentPanelV4.reference', { value: reference })}</span> : null}</div></form>
}
