import React from 'react'
import { useTranslation } from 'react-i18next'
import { IconAlertTriangle, IconCheck, IconChevronRight, IconFileText, IconLayersSubtract, IconLoader2, IconMessage, IconPaperclip, IconPhoto, IconTimelineEvent, IconVideo, IconX } from '@tabler/icons-react'
import { cn } from '../../../utils/cn'
import { AgentPanelV4Markdown } from './AgentPanelV4Markdown'
import { Message, MessageActions, MessageResponse } from './vendor/aiElementsPrimitives'
import type { InterventionData, QueueRowData, TaskCardData, ToolReceipt, V4AssistantStatus, V4TaskStatus, V4ToolStatus } from './agentPanelV4Types'

const statusIcon = (status: V4ToolStatus) => status === 'output-error' || status === 'output-denied' ? <IconAlertTriangle size={14} /> : status === 'output-available' ? <IconCheck size={14} /> : <IconLoader2 size={14} className="animate-spin motion-reduce:animate-none" />
const actionIcon = (action: string) => { const value = action.toLowerCase(); if (value.includes('timeline')) return <IconTimelineEvent size={14} />; if (value.includes('document')) return <IconFileText size={14} />; if (value.includes('canvas') || value.includes('node')) return <IconLayersSubtract size={14} />; if (value.includes('video')) return <IconVideo size={14} />; return <IconPhoto size={14} /> }

export function V4UserBubble({ text, attachment, darkMode = false }: { text: string; attachment?: string; darkMode?: boolean }): JSX.Element {
  return <div className={cn('ml-auto max-w-[88%] rounded-nomi px-3 py-2 text-micro', darkMode ? 'bg-nomi-ink-10 text-nomi-ink' : 'bg-nomi-ink text-nomi-paper')} data-v4-block="user"><p className="m-0">{text}</p>{attachment ? <span className="mt-1 inline-flex items-center gap-1 rounded-nomi-sm bg-nomi-paper/15 px-1.5 py-0.5 text-micro"><IconPaperclip size={12} />{attachment}<IconX size={11} /></span> : null}</div>
}

export function V4AssistantMessage({ text, status, continueLabel }: { text: string; status: V4AssistantStatus; continueLabel: string }): JSX.Element {
  const { t } = useTranslation()
  return <div data-v4-block="assistant" data-status={status}><Message role="assistant"><MessageResponse streaming={status === 'streaming'}><AgentPanelV4Markdown text={text} /></MessageResponse>{status === 'complete' ? <MessageActions copyLabel={t('agentPanelV4.copy')} /> : null}{status === 'interrupted' ? <button type="button" className="mt-1 inline-flex items-center gap-1 text-nomi-ink-60"><IconChevronRight size={12} />{continueLabel}</button> : null}</Message></div>
}

export function V4ToolReceipt({ receipt, statusLabel }: { receipt: ToolReceipt; statusLabel: string }): JSX.Element {
  const { t } = useTranslation()
  const active = receipt.status !== 'output-available' && receipt.status !== 'output-error' && receipt.status !== 'output-denied'
  return <details open={receipt.expanded || active} className="group rounded-nomi-sm" data-v4-block="tool" data-status={receipt.status}><summary className="flex min-h-7 cursor-pointer list-none items-center gap-1.5 rounded-nomi-sm px-2 text-micro text-nomi-ink-60 hover:bg-nomi-ink-05"><IconChevronRight size={12} className="transition-transform group-open:rotate-90" /><span className="text-nomi-accent">{actionIcon(receipt.action)}</span><span className="font-medium text-nomi-ink">{receipt.label}</span>{receipt.skill ? <span className="rounded-pill bg-nomi-accent-soft px-1.5 py-0.5 text-micro text-nomi-accent">{t('agentPanelV4.skill')}</span> : null}{receipt.attachment ? <span className="rounded-pill bg-nomi-ink-05 px-1.5 py-0.5 text-micro"><IconPaperclip size={11} /> {receipt.attachment}</span> : null}<span className="ml-auto flex items-center gap-1 text-nomi-ink-40">{receipt.elapsed ?? statusLabel}{statusIcon(receipt.status)}</span></summary><div className="ml-5 border-l border-nomi-line-soft px-2 py-1 text-micro text-nomi-ink-60"><div>{receipt.detail ?? statusLabel}</div></div></details>
}

const taskStatusIcon = (status: V4TaskStatus) => status === 'complete' ? <IconCheck size={14} /> : status === 'failed' ? <IconAlertTriangle size={14} /> : status === 'stopped' ? <IconX size={14} /> : <IconLoader2 size={14} className="animate-spin motion-reduce:animate-none" />
export function V4TaskCard({ task, labels }: { task: TaskCardData; labels: { status: Record<V4TaskStatus, string>; adopt: string; undo: string } }): JSX.Element {
  return <article className="overflow-hidden rounded-nomi border border-nomi-line bg-nomi-paper" data-v4-block="task" data-status={task.status}><header className="flex items-center gap-1.5 border-b border-nomi-line-soft bg-nomi-ink-05 px-2.5 py-2 text-micro"><IconPhoto size={14} /><strong>{task.title}</strong><span className={cn('ml-auto', task.status === 'failed' && 'text-workbench-danger', task.status === 'complete' && 'text-workbench-success-ink')}>{taskStatusIcon(task.status)} {labels.status[task.status]}</span></header><div className="grid gap-1.5 px-2.5 py-2">{task.detail ? <p className="m-0 text-micro text-nomi-ink-60">{task.detail}</p> : null}{task.progress !== undefined ? <div className="h-1 overflow-hidden rounded-pill bg-nomi-ink-10"><div className="h-full bg-nomi-accent" style={{ width: `${task.progress}%` }} /></div> : null}{task.candidates ? <div className="flex gap-1.5">{task.candidates.map((candidate, index) => <button type="button" key={candidate} className={cn('grid h-10 w-14 place-items-center rounded-nomi-sm border text-micro', index === task.selected ? 'border-nomi-accent bg-nomi-accent-soft text-nomi-accent' : 'border-nomi-line bg-nomi-ink-05')} aria-label={`${labels.adopt} ${candidate}`}>{candidate}</button>)}</div> : null}<div className="flex items-center gap-2 text-micro text-nomi-ink-40"><span className="flex-1">{task.cost ?? ''}</span>{task.status === 'complete' ? <button type="button" className="text-nomi-accent">{labels.undo}</button> : null}</div></div></article>
}

export function V4Intervention({ data, labels }: { data: InterventionData; labels: { confirm: string; reject: string; escalate: string; cancel: string } }): JSX.Element {
  const reversible = data.kind === 'approval-reversible'
  return <aside className="overflow-hidden rounded-nomi border border-nomi-accent bg-nomi-paper" data-v4-block="intervention" data-kind={data.kind}><header className="flex items-center gap-1.5 bg-nomi-accent-soft px-2.5 py-2 text-micro font-semibold text-nomi-accent"><IconMessage size={14} /><span>{data.title}</span>{reversible ? <button type="button" className="ml-auto text-micro font-normal" aria-label={labels.escalate}>{labels.escalate}</button> : null}</header><div className="grid gap-1.5 px-2.5 py-2 text-micro"><p className="m-0 text-nomi-ink">{data.summary}</p>{data.options ? <div className="flex flex-wrap gap-1">{data.options.map((option, index) => <button type="button" key={option} className={cn('rounded-pill border px-2 py-1', index === 0 ? 'border-nomi-accent bg-nomi-accent-soft text-nomi-accent' : 'border-nomi-line')}>{option}</button>)}</div> : null}{data.shots ? <div className="grid gap-1">{data.shots.map((shot, index) => <label key={shot} className="flex items-center gap-1.5"><input type="checkbox" defaultChecked={index !== 2} />{shot}</label>)}</div> : null}{data.cost ? <span className="text-nomi-accent">{data.cost}</span> : null}</div><footer className="flex items-center gap-2 border-t border-nomi-line-soft px-2.5 py-1.5 text-micro"><button type="button" className="rounded-nomi-sm bg-nomi-ink px-2 py-1 text-nomi-paper">{labels.confirm}</button><button type="button" className="text-workbench-danger">{labels.reject}</button>{data.reason ? <span className="ml-auto text-nomi-ink-40">{data.reason}</span> : null}</footer></aside>
}

export function V4Queue({ rows, labels }: { rows: readonly QueueRowData[]; labels: { queued: string; running: string; complete: string; remove: string } }): JSX.Element {
  return <section className="grid gap-1 rounded-nomi-sm border border-nomi-line-soft bg-nomi-ink-05 p-2" data-v4-block="queue">{rows.map((row) => <div key={row.title} className="flex min-h-6 items-center gap-2 text-micro"><span className={cn('size-1.5 rounded-pill bg-nomi-ink-30', row.status === 'running' && 'bg-nomi-accent')} /> <span className={cn(row.status === 'complete' && 'text-nomi-ink-40 line-through')}>{row.title}</span><span className="ml-auto text-nomi-ink-40">{row.status === 'running' ? labels.running : row.status === 'complete' ? labels.complete : row.action ?? labels.queued}</span></div>)}</section>
}
