import React from 'react'
import { useTranslation } from 'react-i18next'
import { IconChevronDown } from '@tabler/icons-react'

export function AgentPanelV4Context({ used = 62400, max = 200000, cost = '¥0.83' }: { used?: number; max?: number; cost?: string }): JSX.Element {
  const { t } = useTranslation()
  const percent = Math.min(100, Math.round((used / max) * 100))
  return <details className="relative" data-v4-block="context"><summary className="flex cursor-pointer list-none items-center gap-1 rounded-pill border border-nomi-line-soft px-2 py-1 text-micro text-nomi-ink-60"><svg aria-label={t('agentPanelV4.context')} role="img" viewBox="0 0 24 24" width="16" height="16" className="text-nomi-accent"><circle cx="12" cy="12" r="10" fill="none" stroke="currentColor" strokeWidth="2" opacity=".25" /><circle cx="12" cy="12" r="10" fill="none" stroke="currentColor" strokeWidth="2" strokeDasharray="62.83 62.83" strokeDashoffset={62.83 * (1 - percent / 100)} strokeLinecap="round" style={{ transform: 'rotate(-90deg)', transformOrigin: 'center' }} /></svg>{percent}%<IconChevronDown size={12} /></summary><div className="absolute bottom-full right-0 z-10 mb-1 w-48 rounded-nomi border border-nomi-line bg-nomi-paper p-2.5 text-micro shadow-nomi-sm"><div className="mb-2 flex items-center justify-between"><strong>{percent}%</strong><span className="text-nomi-ink-40">{used.toLocaleString()} / {max.toLocaleString()}</span></div><div className="mb-2 h-1 overflow-hidden rounded-pill bg-nomi-ink-10"><div className="h-full bg-nomi-accent" style={{ width: `${percent}%` }} /></div><dl className="grid gap-1"><div className="flex justify-between"><dt>{t('agentPanelV4.input')}</dt><dd>{t('agentPanelV4.inputsCount')}</dd></div><div className="flex justify-between"><dt>{t('agentPanelV4.output')}</dt><dd>{t('agentPanelV4.outputsCount')}</dd></div><div className="flex justify-between"><dt>{t('agentPanelV4.reasoning')}</dt><dd>{t('agentPanelV4.reasoningCount')}</dd></div><div className="flex justify-between"><dt>{t('agentPanelV4.cache')}</dt><dd>{t('agentPanelV4.cacheCount')}</dd></div></dl><footer className="mt-2 flex justify-between border-t border-nomi-line-soft pt-2"><span>{t('agentPanelV4.threadCost')}</span><strong>{cost}</strong></footer></div></details>
}
