// 设计实验室 · 屏「视频节点的下一步」· 剪辑面板与剪辑结果。
// 本文件由四轨（中浅 / 英浅 / 中暗 / 英暗）展开生成，改格子改生成输入而不是手改这里的重复项。
import React from 'react'
import type { LabState } from '../../labScreen'
import { ClipStage } from '../videoNodeNextClipPanel'
import { SceneStage } from '../videoNodeNextCanvasKit'

const SOURCE = 'docs/plan/2026-10-09-video-node-next.md §3 剪辑'

export const VN_CLIP_STATES: readonly LabState[] = [
  {
    id: 'vn-03-clip-open-zh',
    name: '点「剪辑」· 面板贴着节点下沿弹出：入点出点在两头、读数全长（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    render: () => <ClipStage locale="zh-CN" scenario={{ kind: 'open' }} />,
  },
  {
    id: 'vn-03-clip-open-en',
    name: '点「剪辑」· 面板贴着节点下沿弹出：入点出点在两头、读数全长（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    render: () => <ClipStage locale="en" scenario={{ kind: 'open' }} />,
  },
  {
    id: 'vn-03-clip-open-zh-dark',
    name: '点「剪辑」· 面板贴着节点下沿弹出：入点出点在两头、读数全长（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    scheme: 'dark',
    render: () => <ClipStage locale="zh-CN" scenario={{ kind: 'open' }} />,
  },
  {
    id: 'vn-03-clip-open-en-dark',
    name: '点「剪辑」· 面板贴着节点下沿弹出：入点出点在两头、读数全长（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    scheme: 'dark',
    render: () => <ClipStage locale="en" scenario={{ kind: 'open' }} />,
  },
  {
    id: 'vn-04-clip-drag-in-zh',
    name: '拖动入点中 · 出点已设在 18.0，入点手柄按住不放，读数高亮入点、预览画面跟着入点走（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    render: () => <ClipStage locale="zh-CN" scenario={{ kind: 'drag-in', dragToSeconds: 6, outSeconds: 18 }} />,
  },
  {
    id: 'vn-04-clip-drag-in-en',
    name: '拖动入点中 · 出点已设在 18.0，入点手柄按住不放，读数高亮入点、预览画面跟着入点走（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    render: () => <ClipStage locale="en" scenario={{ kind: 'drag-in', dragToSeconds: 6, outSeconds: 18 }} />,
  },
  {
    id: 'vn-04-clip-drag-in-zh-dark',
    name: '拖动入点中 · 出点已设在 18.0，入点手柄按住不放，读数高亮入点、预览画面跟着入点走（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    scheme: 'dark',
    render: () => <ClipStage locale="zh-CN" scenario={{ kind: 'drag-in', dragToSeconds: 6, outSeconds: 18 }} />,
  },
  {
    id: 'vn-04-clip-drag-in-en-dark',
    name: '拖动入点中 · 出点已设在 18.0，入点手柄按住不放，读数高亮入点、预览画面跟着入点走（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    scheme: 'dark',
    render: () => <ClipStage locale="en" scenario={{ kind: 'drag-in', dragToSeconds: 6, outSeconds: 18 }} />,
  },
  {
    id: 'vn-05-clip-preview-zh',
    name: '预览中 · 入点 6.0 出点 18.0 已设好，只播保留的这一段（播放头在 11.5）（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    render: () => <ClipStage locale="zh-CN" scenario={{ kind: 'preview', fromSeconds: 6, toSeconds: 18, atSeconds: 11.5 }} />,
  },
  {
    id: 'vn-05-clip-preview-en',
    name: '预览中 · 入点 6.0 出点 18.0 已设好，只播保留的这一段（播放头在 11.5）（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    render: () => <ClipStage locale="en" scenario={{ kind: 'preview', fromSeconds: 6, toSeconds: 18, atSeconds: 11.5 }} />,
  },
  {
    id: 'vn-05-clip-preview-zh-dark',
    name: '预览中 · 入点 6.0 出点 18.0 已设好，只播保留的这一段（播放头在 11.5）（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    scheme: 'dark',
    render: () => <ClipStage locale="zh-CN" scenario={{ kind: 'preview', fromSeconds: 6, toSeconds: 18, atSeconds: 11.5 }} />,
  },
  {
    id: 'vn-05-clip-preview-en-dark',
    name: '预览中 · 入点 6.0 出点 18.0 已设好，只播保留的这一段（播放头在 11.5）（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/ClipNodeTimeline.tsx:74',
    coverage: 'component-only',
    scheme: 'dark',
    render: () => <ClipStage locale="en" scenario={{ kind: 'preview', fromSeconds: 6, toSeconds: 18, atSeconds: 11.5 }} />,
  },
  {
    id: 'vn-06-clip-done-zh',
    name: '确认之后 · 原视频右侧新出一张剪辑结果视频卡并连线，原视频不变，面板收起（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/extractVideoFrameToNode.ts:49',
    coverage: 'shell',
    render: () => <SceneStage locale="zh-CN" scene="trim-done" />,
  },
  {
    id: 'vn-06-clip-done-en',
    name: '确认之后 · 原视频右侧新出一张剪辑结果视频卡并连线，原视频不变，面板收起（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/extractVideoFrameToNode.ts:49',
    coverage: 'shell',
    render: () => <SceneStage locale="en" scene="trim-done" />,
  },
  {
    id: 'vn-06-clip-done-zh-dark',
    name: '确认之后 · 原视频右侧新出一张剪辑结果视频卡并连线，原视频不变，面板收起（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/extractVideoFrameToNode.ts:49',
    coverage: 'shell',
    scheme: 'dark',
    render: () => <SceneStage locale="zh-CN" scene="trim-done" />,
  },
  {
    id: 'vn-06-clip-done-en-dark',
    name: '确认之后 · 原视频右侧新出一张剪辑结果视频卡并连线，原视频不变，面板收起（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/extractVideoFrameToNode.ts:49',
    coverage: 'shell',
    scheme: 'dark',
    render: () => <SceneStage locale="en" scene="trim-done" />,
  },
  {
    id: 'vn-07-clip-running-zh',
    name: '确认之后、剪辑进行中 · 新卡顶上一条进度加取消（和提取深度同一条），原视频不动（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeGeneratingOverlay.tsx:30',
    coverage: 'shell',
    render: () => <SceneStage locale="zh-CN" scene="trim-running" />,
  },
  {
    id: 'vn-07-clip-running-en',
    name: '确认之后、剪辑进行中 · 新卡顶上一条进度加取消（和提取深度同一条），原视频不动（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeGeneratingOverlay.tsx:30',
    coverage: 'shell',
    render: () => <SceneStage locale="en" scene="trim-running" />,
  },
  {
    id: 'vn-07-clip-running-zh-dark',
    name: '确认之后、剪辑进行中 · 新卡顶上一条进度加取消（和提取深度同一条），原视频不动（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeGeneratingOverlay.tsx:30',
    coverage: 'shell',
    scheme: 'dark',
    render: () => <SceneStage locale="zh-CN" scene="trim-running" />,
  },
  {
    id: 'vn-07-clip-running-en-dark',
    name: '确认之后、剪辑进行中 · 新卡顶上一条进度加取消（和提取深度同一条），原视频不动（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeGeneratingOverlay.tsx:30',
    coverage: 'shell',
    scheme: 'dark',
    render: () => <SceneStage locale="en" scene="trim-running" />,
  },
]
