// 设计实验室 · 屏「视频节点的下一步」· 失败态与缩小画布。
// 本文件由四轨（中浅 / 英浅 / 中暗 / 英暗）展开生成，改格子改生成输入而不是手改这里的重复项。
import React from 'react'
import type { LabState } from '../../labScreen'
import { SceneStage } from '../videoNodeNextCanvasKit'
import { ToolbarStage } from '../videoNodeNextToolbarKit'
import { ClipStage } from '../videoNodeNextClipPanel'

const SOURCE = 'docs/plan/2026-10-09-video-node-next.md §5 失败态 / §6 缩小画布'

export const VN_FAILURE_ZOOM_STATES: readonly LabState[] = [
  {
    id: 'vn-11-frame-failed-zh',
    name: '截帧失败 · 新图片卡带现役错误卡，原视频不动（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/BaseGenerationNode.tsx:350',
    coverage: 'shell',
    render: () => <SceneStage locale="zh-CN" scene="frame-failed" />,
  },
  {
    id: 'vn-11-frame-failed-en',
    name: '截帧失败 · 新图片卡带现役错误卡，原视频不动（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/BaseGenerationNode.tsx:350',
    coverage: 'shell',
    render: () => <SceneStage locale="en" scene="frame-failed" />,
  },
  {
    id: 'vn-11-frame-failed-zh-dark',
    name: '截帧失败 · 新图片卡带现役错误卡，原视频不动（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/BaseGenerationNode.tsx:350',
    coverage: 'shell',
    scheme: 'dark',
    render: () => <SceneStage locale="zh-CN" scene="frame-failed" />,
  },
  {
    id: 'vn-11-frame-failed-en-dark',
    name: '截帧失败 · 新图片卡带现役错误卡，原视频不动（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/BaseGenerationNode.tsx:350',
    coverage: 'shell',
    scheme: 'dark',
    render: () => <SceneStage locale="en" scene="frame-failed" />,
  },
  {
    id: 'vn-12-trim-failed-zh',
    name: '剪辑失败 · 新视频卡带现役错误卡，原视频不动（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/BaseGenerationNode.tsx:350',
    coverage: 'shell',
    render: () => <SceneStage locale="zh-CN" scene="trim-failed" />,
  },
  {
    id: 'vn-12-trim-failed-en',
    name: '剪辑失败 · 新视频卡带现役错误卡，原视频不动（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/BaseGenerationNode.tsx:350',
    coverage: 'shell',
    render: () => <SceneStage locale="en" scene="trim-failed" />,
  },
  {
    id: 'vn-12-trim-failed-zh-dark',
    name: '剪辑失败 · 新视频卡带现役错误卡，原视频不动（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/BaseGenerationNode.tsx:350',
    coverage: 'shell',
    scheme: 'dark',
    render: () => <SceneStage locale="zh-CN" scene="trim-failed" />,
  },
  {
    id: 'vn-12-trim-failed-en-dark',
    name: '剪辑失败 · 新视频卡带现役错误卡，原视频不动（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/BaseGenerationNode.tsx:350',
    coverage: 'shell',
    scheme: 'dark',
    render: () => <SceneStage locale="en" scene="trim-failed" />,
  },
  {
    id: 'vn-13-zoom50-toolbar-zh',
    name: '画布缩小到 50% · 浮条与「截帧▾」菜单仍是屏幕原尺寸、能点（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeFloatingToolbar.tsx:62',
    coverage: 'component-only',
    capture: 'viewport',
    render: () => <ToolbarStage locale="zh-CN" open="capture-frame" zoom={0.5} />,
  },
  {
    id: 'vn-13-zoom50-toolbar-en',
    name: '画布缩小到 50% · 浮条与「截帧▾」菜单仍是屏幕原尺寸、能点（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeFloatingToolbar.tsx:62',
    coverage: 'component-only',
    capture: 'viewport',
    render: () => <ToolbarStage locale="en" open="capture-frame" zoom={0.5} />,
  },
  {
    id: 'vn-13-zoom50-toolbar-zh-dark',
    name: '画布缩小到 50% · 浮条与「截帧▾」菜单仍是屏幕原尺寸、能点（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeFloatingToolbar.tsx:62',
    coverage: 'component-only',
    capture: 'viewport',
    scheme: 'dark',
    render: () => <ToolbarStage locale="zh-CN" open="capture-frame" zoom={0.5} />,
  },
  {
    id: 'vn-13-zoom50-toolbar-en-dark',
    name: '画布缩小到 50% · 浮条与「截帧▾」菜单仍是屏幕原尺寸、能点（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeFloatingToolbar.tsx:62',
    coverage: 'component-only',
    capture: 'viewport',
    scheme: 'dark',
    render: () => <ToolbarStage locale="en" open="capture-frame" zoom={0.5} />,
  },
  {
    id: 'vn-14-zoom50-clip-zh',
    name: '画布缩小到 50% · 剪辑面板仍是屏幕原尺寸、手柄能抓（中文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeFloatingToolbar.tsx:62',
    coverage: 'component-only',
    render: () => <ClipStage locale="zh-CN" scenario={{ kind: 'preview', fromSeconds: 6, toSeconds: 18, atSeconds: 11.5 }} zoom={0.5} />,
  },
  {
    id: 'vn-14-zoom50-clip-en',
    name: '画布缩小到 50% · 剪辑面板仍是屏幕原尺寸、手柄能抓（英文 · 浅色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeFloatingToolbar.tsx:62',
    coverage: 'component-only',
    render: () => <ClipStage locale="en" scenario={{ kind: 'preview', fromSeconds: 6, toSeconds: 18, atSeconds: 11.5 }} zoom={0.5} />,
  },
  {
    id: 'vn-14-zoom50-clip-zh-dark',
    name: '画布缩小到 50% · 剪辑面板仍是屏幕原尺寸、手柄能抓（中文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeFloatingToolbar.tsx:62',
    coverage: 'component-only',
    scheme: 'dark',
    render: () => <ClipStage locale="zh-CN" scenario={{ kind: 'preview', fromSeconds: 6, toSeconds: 18, atSeconds: 11.5 }} zoom={0.5} />,
  },
  {
    id: 'vn-14-zoom50-clip-en-dark',
    name: '画布缩小到 50% · 剪辑面板仍是屏幕原尺寸、手柄能抓（英文 · 暗色）',
    source: SOURCE,
    mirrors: 'src/workbench/generationCanvas/nodes/NodeFloatingToolbar.tsx:62',
    coverage: 'component-only',
    scheme: 'dark',
    render: () => <ClipStage locale="en" scenario={{ kind: 'preview', fromSeconds: 6, toSeconds: 18, atSeconds: 11.5 }} zoom={0.5} />,
  },
]
