// 「去掉强调色描边」样张：八格 × 「现在 / 改后」× 亮 / 暗。规则与普查见 docs/plan/2026-10-10-no-accent-outline.md。
import type { LabState } from '../../labScreen'
import { renderNaoCell } from '../noAccentOutlineLabKit'

const SOURCE = '用户 10-10 拍板方向（蓝色描边都删）· 协调会话规则 1-5 · 普查见 docs/plan/2026-10-10-no-accent-outline.md'

export const NO_ACCENT_OUTLINE_STATES: readonly LabState[] = [
  {
    id: 'nao-single-now-light',
    name: '01 单选图片节点 · 现在（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('single', 'now'),
  },
  {
    id: 'nao-single-after-light',
    name: '01 单选图片节点 · 改后（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('single', 'after'),
  },
  {
    id: 'nao-single-now-dark',
    name: '01 单选图片节点 · 现在（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('single', 'now'),
  },
  {
    id: 'nao-single-after-dark',
    name: '01 单选图片节点 · 改后（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('single', 'after'),
  },
  {
    id: 'nao-multi-now-light',
    name: '02 框选三个节点 · 现在（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('multi', 'now'),
  },
  {
    id: 'nao-multi-after-light',
    name: '02 框选三个节点 · 改后（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('multi', 'after'),
  },
  {
    id: 'nao-multi-now-dark',
    name: '02 框选三个节点 · 现在（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('multi', 'now'),
  },
  {
    id: 'nao-multi-after-dark',
    name: '02 框选三个节点 · 改后（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('multi', 'after'),
  },
  {
    id: 'nao-group-now-light',
    name: '03 选中分组 · 现在（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('group', 'now'),
  },
  {
    id: 'nao-group-after-light',
    name: '03 选中分组 · 改后（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('group', 'after'),
  },
  {
    id: 'nao-group-now-dark',
    name: '03 选中分组 · 现在（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('group', 'now'),
  },
  {
    id: 'nao-group-after-dark',
    name: '03 选中分组 · 改后（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('group', 'after'),
  },
  {
    id: 'nao-asset-now-light',
    name: '04 素材库选中两个素材 · 现在（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('asset', 'now'),
  },
  {
    id: 'nao-asset-after-light',
    name: '04 素材库选中两个素材 · 改后（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('asset', 'after'),
  },
  {
    id: 'nao-asset-now-dark',
    name: '04 素材库选中两个素材 · 现在（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('asset', 'now'),
  },
  {
    id: 'nao-asset-after-dark',
    name: '04 素材库选中两个素材 · 改后（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('asset', 'after'),
  },
  {
    id: 'nao-list-now-light',
    name: '05 左栏当前项 · 现在（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('list', 'now'),
  },
  {
    id: 'nao-list-after-light',
    name: '05 左栏当前项 · 改后（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('list', 'after'),
  },
  {
    id: 'nao-list-now-dark',
    name: '05 左栏当前项 · 现在（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('list', 'now'),
  },
  {
    id: 'nao-list-after-dark',
    name: '05 左栏当前项 · 改后（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('list', 'after'),
  },
  {
    id: 'nao-input-now-light',
    name: '06 Agent 输入框聚焦 · 现在（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('input', 'now'),
  },
  {
    id: 'nao-input-after-light',
    name: '06 Agent 输入框聚焦 · 改后（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('input', 'after'),
  },
  {
    id: 'nao-input-now-dark',
    name: '06 Agent 输入框聚焦 · 现在（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('input', 'now'),
  },
  {
    id: 'nao-input-after-dark',
    name: '06 Agent 输入框聚焦 · 改后（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('input', 'after'),
  },
  {
    id: 'nao-keyboard-now-light',
    name: '07 键盘焦点落在按钮 · 现在（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('keyboard', 'now'),
  },
  {
    id: 'nao-keyboard-after-light',
    name: '07 键盘焦点落在按钮 · 改后（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('keyboard', 'after'),
  },
  {
    id: 'nao-keyboard-now-dark',
    name: '07 键盘焦点落在按钮 · 现在（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('keyboard', 'now'),
  },
  {
    id: 'nao-keyboard-after-dark',
    name: '07 键盘焦点落在按钮 · 改后（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('keyboard', 'after'),
  },
  {
    id: 'nao-card-now-light',
    name: '08 Agent 面板提示卡（蓝边） · 现在（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('card', 'now'),
  },
  {
    id: 'nao-card-after-light',
    name: '08 Agent 面板提示卡（蓝边） · 改后（亮）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'light',
    render: () => renderNaoCell('card', 'after'),
  },
  {
    id: 'nao-card-now-dark',
    name: '08 Agent 面板提示卡（蓝边） · 现在（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('card', 'now'),
  },
  {
    id: 'nao-card-after-dark',
    name: '08 Agent 面板提示卡（蓝边） · 改后（暗）',
    source: SOURCE,
    coverage: 'component-only',
    scheme: 'dark',
    render: () => renderNaoCell('card', 'after'),
  },
]
