import { describe, expect, it } from "vitest";
import type { ProviderAdapterDraft } from "./types";
import { adapterRevisionDigest, assertAdapterModeInvariants, validateProviderAdapterDraft } from "./validator";

const baseDraft = (): ProviderAdapterDraft => ({
  provider: {
    baseUrl: "https://api.example.com/v1",
    authType: "bearer",
  },
  sources: [
    {
      url: "https://docs.example.com/api/images",
      title: "Images API",
      evidence: "POST /v1/images/generations accepts model and prompt.",
    },
  ],
  models: [
    {
      modelKey: "paint-v2",
      labelZh: "Paint V2",
      kind: "image",
      modes: [
        {
          taskKind: "text_to_image",
          create: {
            method: "POST",
            path: "/images/generations",
            body: {
              model: "{{model.modelKey}}",
              prompt: "{{request.prompt}}",
              size: "{{request.params.size}}",
            },
            response_mapping: { image_url: "data.0.url" },
          },
          testParams: { size: "1024x1024" },
          sourceUrls: ["https://docs.example.com/api/images"],
        },
      ],
    },
  ],
});

describe("validateProviderAdapterDraft", () => {
  it("accepts a declarative same-origin adapter for a selected model", () => {
    const result = validateProviderAdapterDraft(baseDraft(), {
      providerBaseUrl: "https://api.example.com/v1",
      selectedModelKeys: ["paint-v2"],
    });

    expect(result.models[0]?.modes[0]?.create.method).toBe("POST");
  });

  it("rejects an absolute operation URL on another origin", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.path = "https://attacker.invalid/steal";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/same origin/i);
  });

  it("rejects relative traversal paths", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.path = "/images/../admin";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/traversal/i);
  });

  it("rejects executable transforms generated by the model", () => {
    const draft = baseDraft();
    (draft.models[0].modes[0].create as unknown as Record<string, unknown>).request_transform = "eval-js";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/request_transform/i);
  });

  it("rejects template roots outside the allowlist", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.body = { key: "{{process.env.SECRET}}" };

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/template root/i);
  });

  it("rejects prototype-chain access even when the template root is allowed", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.body = { key: "{{request.constructor.constructor}}" };

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/template path/i);
  });

  it("rejects prototype-polluting object keys from generated JSON", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.body = JSON.parse('{"constructor":{"prototype":{"polluted":true}}}');

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/object key/i);
  });

  it("rejects a model that the user did not select", () => {
    const draft = baseDraft();
    draft.models.push({
      ...draft.models[0],
      modelKey: "surprise-model",
      modes: [...draft.models[0].modes],
    });

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/not selected/i);
  });

  it("rejects an adapter that silently omits a selected model", () => {
    expect(() =>
      validateProviderAdapterDraft(baseDraft(), {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2", "video-v3"],
      }),
    ).toThrow(/missing selected model/i);
  });

  it("requires an explicit reference parameter for reference-image modes", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].taskKind = "image_edit";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/referenceParam/i);
  });

  it("requires the reference value shape so the runtime cannot guess between one URL and an array", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].taskKind = "image_edit";
    draft.models[0].modes[0].referenceParam = "referenceImages";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/referenceShape/i);
  });

  it("requires a media result mapping on either create or query", () => {
    const draft = baseDraft();
    delete draft.models[0].modes[0].create.response_mapping;

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/media result mapping/i);
  });

  it("accepts a separate result operation after an async status query", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.response_mapping = { task_id: "request_id" };
    draft.models[0].modes[0].create.provider_meta_mapping = { task_id: "request_id" };
    draft.models[0].modes[0].query = {
      method: "GET",
      path: "/requests/{{providerMeta.task_id}}/status",
      response_mapping: { status: "status" },
    };
    draft.models[0].modes[0].result = {
      method: "GET",
      path: "/requests/{{providerMeta.task_id}}",
      response_mapping: { image_url: "images.0.url" },
    };
    draft.models[0].modes[0].statusMapping = { succeeded: ["COMPLETED"] };

    expect(() => validateProviderAdapterDraft(draft, {
      providerBaseUrl: "https://api.example.com/v1",
      selectedModelKeys: ["paint-v2"],
    })).not.toThrow();
  });

  it("rejects a result operation without a status query", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].result = {
      method: "GET",
      path: "/requests/{{providerMeta.task_id}}",
      response_mapping: { image_url: "images.0.url" },
    };

    expect(() => validateProviderAdapterDraft(draft, {
      providerBaseUrl: "https://api.example.com/v1",
      selectedModelKeys: ["paint-v2"],
    })).toThrow(/result without query/i);
  });

  it("rejects mode evidence URLs that were not included in the discovered official sources", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].sourceUrls = ["https://untrusted.invalid/fake-docs"];

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/source url/i);
  });

  it("rejects response mapping keys the runtime cannot consume", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.response_mapping = { outputUrl: "data.0.url" };

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/response mapping key/i);
  });

  it("rejects prototype-chain response paths", () => {
    const draft = baseDraft();
    draft.models[0].modes[0].create.response_mapping = { image_url: "data.constructor.prototype.url" };

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/response path/i);
  });

  it("rejects task kinds that do not match the billing model kind", () => {
    const draft = baseDraft();
    draft.models[0].kind = "text";

    expect(() =>
      validateProviderAdapterDraft(draft, {
        providerBaseUrl: "https://api.example.com/v1",
        selectedModelKeys: ["paint-v2"],
      }),
    ).toThrow(/model kind/i);
  });

  it("accepts declared binary audio without inventing an audio URL", () => {
    const draft = baseDraft();
    draft.models[0].kind = "audio";
    draft.models[0].modes[0] = {
      taskKind: "text_to_audio",
      create: {
        method: "POST",
        path: "/audio",
        body: { text: "{{request.prompt}}" },
        audioResponse: { type: "binary", contentType: "audio/mpeg", extension: "mp3" },
      },
      sourceUrls: ["https://docs.example.com/api/images"],
    };

    expect(validateProviderAdapterDraft(draft, {
      providerBaseUrl: "https://api.example.com/v1",
      selectedModelKeys: ["paint-v2"],
    }).models[0].modes[0].create.audioResponse).toMatchObject({ type: "binary" });
  });

  it("accepts declaration-driven transcription multipart with a text result", () => {
    const draft = baseDraft();
    draft.models[0].kind = "audio";
    draft.models[0].modes[0] = {
      taskKind: "transcribe",
      create: {
        method: "POST",
        path: "/speech-to-text",
        multipart: {
          fields: { model_id: "scribe_v2" },
          fileField: "file",
          fileSource: "{{request.params.file}}",
          fileKind: "audio",
        },
        response_mapping: { text: "text" },
      },
      sourceUrls: ["https://docs.example.com/api/images"],
    };

    expect(() => validateProviderAdapterDraft(draft, {
      providerBaseUrl: "https://api.example.com/v1",
      selectedModelKeys: ["paint-v2"],
    })).not.toThrow();
  });

  it("rejects unsafe JSON audio paths and manual multipart boundaries", () => {
    const draft = baseDraft();
    draft.models[0].kind = "audio";
    draft.models[0].modes[0] = {
      taskKind: "text_to_audio",
      create: {
        method: "POST",
        path: "/audio",
        audioResponse: { type: "json", dataPath: "data.constructor.audio", encoding: "hex", contentType: "audio/mpeg", extension: "mp3" },
      },
      sourceUrls: ["https://docs.example.com/api/images"],
    };
    expect(() => validateProviderAdapterDraft(draft, {
      providerBaseUrl: "https://api.example.com/v1",
      selectedModelKeys: ["paint-v2"],
    })).toThrow(/audioResponse.*path/i);

    draft.models[0].modes[0].create = {
      method: "POST",
      path: "/speech-to-text",
      headers: { "Content-Type": "multipart/form-data" },
      multipart: { fileField: "file", fileSource: "{{request.params.file}}", fileKind: "audio" },
      response_mapping: { audio_url: "audio_url" },
    };
    expect(() => validateProviderAdapterDraft(draft, {
      providerBaseUrl: "https://api.example.com/v1",
      selectedModelKeys: ["paint-v2"],
    })).toThrow(/boundary/i);
  });
});

// 类级锁：说明卡有**两个生产者**（compiler 的 AI 编译路径、builtinOpenAiCompatibleDraft 的内置模板），
// 语义不变量必须只有一份、两边都穿过。此前校验只挂在 AI 那条路上，内置模板一次都没被看过，
// 于是「参考类模式必须声明 referenceParam/referenceShape」对它结构性失效——不是有人手滑漏写，
// 是这条规则根本管不到那条路（2026-09-03 真中转实测挖出，见同名根因合同）。
describe("assertAdapterModeInvariants（两个生产者共用的那一份）", () => {
  const referenceMode = (taskKind: "image_edit" | "image_to_video" | "image_to_audio" | "image_to_3d") => ({
    image_edit: { kind: "image" as const, path: "/v1/images/edits", mapping: { image_url: "url" } },
    image_to_video: { kind: "video" as const, path: "/v1/video/generations", mapping: { video_url: "url" } },
    image_to_audio: { kind: "audio" as const, path: "/v1/audio/speech", mapping: { audio_url: "url" } },
    image_to_3d: { kind: "model3d" as const, path: "/v1/3d/generations", mapping: { model_url: "url" } },
  })[taskKind];

  // 全集以 validator.ts 的 referenceTaskKinds 为准；四种都锁，防止将来加了第五种却漏挂。
  for (const taskKind of ["image_edit", "image_to_video", "image_to_audio", "image_to_3d"] as const) {
    const shape = referenceMode(taskKind);

    it(`${taskKind} 缺 referenceParam 必须当场抛（不许留到运行期静默失败）`, () => {
      expect(() =>
        assertAdapterModeInvariants({
          modelKey: "m-1",
          kind: shape.kind,
          modes: [{
            taskKind,
            create: { method: "POST", path: shape.path, response_mapping: shape.mapping },
            referenceShape: "array",
            sourceUrls: [],
          }],
        }),
      ).toThrow(/requires referenceParam/);
    });

    it(`${taskKind} 缺 referenceShape 必须当场抛`, () => {
      expect(() =>
        assertAdapterModeInvariants({
          modelKey: "m-1",
          kind: shape.kind,
          modes: [{
            taskKind,
            create: { method: "POST", path: shape.path, response_mapping: shape.mapping },
            referenceParam: "reference_images",
            sourceUrls: [],
          }],
        }),
      ).toThrow(/requires referenceShape/);
    });
  }

  // 非参考类模式不受这条约束——别把闸门开得比规则宽（那会逼着 text_to_image 也编一个参考键）。
  it("非参考类模式不要求参考声明（闸门不许比规则更宽）", () => {
    expect(() =>
      assertAdapterModeInvariants({
        modelKey: "m-1",
        kind: "image",
        modes: [{
          taskKind: "text_to_image",
          create: { method: "POST", path: "/v1/images/generations", response_mapping: { image_url: "url" } },
          sourceUrls: [],
        }],
      }),
    ).not.toThrow();
  });

  // 抽取时差点改坏的那条顺序：先说「这个键不支持」，而不是笼统的「缺媒体映射」。
  it("不支持的响应映射键先于「缺媒体映射」报出（错误顺序不许被抽取改掉）", () => {
    expect(() =>
      assertAdapterModeInvariants({
        modelKey: "m-1",
        kind: "image",
        modes: [{
          taskKind: "text_to_image",
          create: { method: "POST", path: "/v1/images/generations", response_mapping: { totally_unknown: "url" } },
          sourceUrls: [],
        }],
      }),
    ).toThrow(/unsupported response mapping key/);
  });
});

describe("adapterRevisionDigest", () => {
  it("is stable across object key insertion order", () => {
    const left = baseDraft();
    const right = baseDraft();
    right.models[0].modes[0].testParams = { quality: "high", size: "1024x1024" };
    left.models[0].modes[0].testParams = { size: "1024x1024", quality: "high" };

    expect(adapterRevisionDigest(left)).toBe(adapterRevisionDigest(right));
  });
});
