import React from 'react'
import type { LabState } from '../../labScreen'
import { MigrationStage } from '../migrationStage'

// MCP 第 3 段迁移提示（画布 v5）：询问 / 改好 / 部分没改成 / 新连接方式用不了 / 点了以后再说之后不出现。
// 每种 × 中英 × 浅暗；舞台是生产 ConnectAssistantCard + 主进程会给的形状，按钮由舞台真点。
// 这个文件由同目录生成的清单展开，id 必须是字面量（labStates.mjs 用源码正则解析）。
const SOURCE = 'docs/plan/2026-10-09-mcp-host-migration.md · 界面（画布 v5 迁移提示）'
const MIRRORS = 'src/ui/onboarding/ConnectAssistantCard.tsx:177'

export const HOST_CONFIG_MIGRATION_STATES: readonly LabState[] = [
  {
    id: 'host-config-02-migration-ask-zh-light',
    name: '迁移提示 · 询问 · 中文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="ask" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-ask-zh-dark',
    name: '迁移提示 · 询问 · 中文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="ask" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-ask-en-light',
    name: '迁移提示 · 询问 · 英文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="ask" locale="en" />,
  },
  {
    id: 'host-config-02-migration-ask-en-dark',
    name: '迁移提示 · 询问 · 英文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="ask" locale="en" />,
  },
  {
    id: 'host-config-02-migration-done-zh-light',
    name: '迁移提示 · 改好 · 中文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="done" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-done-zh-dark',
    name: '迁移提示 · 改好 · 中文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="done" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-done-en-light',
    name: '迁移提示 · 改好 · 英文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="done" locale="en" />,
  },
  {
    id: 'host-config-02-migration-done-en-dark',
    name: '迁移提示 · 改好 · 英文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="done" locale="en" />,
  },
  {
    id: 'host-config-02-migration-partial-zh-light',
    name: '迁移提示 · 部分没改成 · 中文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="partial" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-partial-zh-dark',
    name: '迁移提示 · 部分没改成 · 中文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="partial" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-partial-en-light',
    name: '迁移提示 · 部分没改成 · 英文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="partial" locale="en" />,
  },
  {
    id: 'host-config-02-migration-partial-en-dark',
    name: '迁移提示 · 部分没改成 · 英文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="partial" locale="en" />,
  },
  {
    id: 'host-config-02-migration-unavailable-zh-light',
    name: '迁移提示 · 新连接方式用不了 · 中文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="unavailable" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-unavailable-zh-dark',
    name: '迁移提示 · 新连接方式用不了 · 中文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="unavailable" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-unavailable-en-light',
    name: '迁移提示 · 新连接方式用不了 · 英文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="unavailable" locale="en" />,
  },
  {
    id: 'host-config-02-migration-unavailable-en-dark',
    name: '迁移提示 · 新连接方式用不了 · 英文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="unavailable" locale="en" />,
  },
  {
    id: 'host-config-02-migration-deferred-zh-light',
    name: '迁移提示 · 点了以后再说 · 中文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="deferred" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-deferred-zh-dark',
    name: '迁移提示 · 点了以后再说 · 中文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="deferred" locale="zh-CN" />,
  },
  {
    id: 'host-config-02-migration-deferred-en-light',
    name: '迁移提示 · 点了以后再说 · 英文·浅色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'light',
    render: () => <MigrationStage phase="deferred" locale="en" />,
  },
  {
    id: 'host-config-02-migration-deferred-en-dark',
    name: '迁移提示 · 点了以后再说 · 英文·暗色',
    source: SOURCE,
    mirrors: MIRRORS,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <MigrationStage phase="deferred" locale="en" />,
  },
]
