// 桌面侧（主进程）文案表 + 取词函数——**electron-free**。
//
// 为什么不住在 i18n.ts 里（2026-09-18）：i18n.ts 顶上有 `import { app, ipcMain } from "electron"`
// 与 settingsRoot（后者同样引 app），所以它只能在主进程里被 import。而 catalog 层有模块
// （assetLocalization.ts 的 collectLocalAssetUrls）**渲染层本来就在引**，那条链一旦碰到
// desktopT，整条渲染包就把主进程 API 拉了进来：模块求值当场抛
// 「does not provide an export named 'app'」，设计实验室整页起不来。
//
// 拆法与同文件对 desktopLocale.ts 的处理完全一致：纯逻辑住在 electron-free 的模块里，
// i18n.ts 引来再原样导出，对既有消费者的公开面不变（P1：函数只此一处定义，i18n 只是转口）。

import { getDesktopLocale, type DesktopLocale } from "./desktopLocale";

const translations = {
  "zh-CN": {
    "sourceTask.missing": "请连接一段符合要求的已生成视频，或填写它的源任务 ID；本次尚未提交生成。",
    "agent.legacySummary": "旧版摘要：",
    "agent.legacyUnverifiedTool": "旧版工具结果未验证。",
    "credential.invalid": "密钥验证失败，请检查密钥和权限后重试。",
    "credential.revalidationUnavailable": "密钥已保存，尚未验证。请联网后重试，届时会自动复验。",
    "credential.validationUnavailable": "暂时无法验证密钥，请检查接口地址和网络后重试。",
    "credential.previousKept": "原密钥和连接已保留。",
    "credential.changed": "验证期间连接已更改，请重新保存。原密钥未覆盖。",
    "workspace.selectTitle": "选择 Nomi 项目文件夹",
    "workspace.openButton": "打开文件夹",
    "workspace.invalidFolder": "未选择有效的文件夹",
    "workspace.protectedFolder": "“{{path}}” 是主目录或系统关键目录，不能作为 Nomi 项目文件夹（会污染你的照片/音乐/系统文件）。请新建或另选一个空文件夹。",
    "workspace.initializeTitle": "初始化 Nomi 项目文件夹？",
    "workspace.initializeDetail": "Nomi 会在此文件夹创建 .nomi/，并把生成的图片、视频保存到 assets/ 和 exports/.\n\n{{path}}",
    "common.cancel": "取消",
    "common.initialize": "初始化",
    "common.unknownError": "未知错误",
    "dreamina.reusedLogin": "即梦已复用本机登录态，无需重新扫码。Nomi 会刷新当前登录状态。",
    "dreamina.loginStartFailed": "发起即梦登录失败：{{message}}",
    "dreamina.missingDeviceCode": "缺少 device_code",
    "dreamina.loginSuccess": "登录成功",
    "dreamina.waiting": "等待授权中…",
    "dreamina.loginFailed": "登录失败",
    "dreamina.installed": "即梦 CLI 已安装",
    "dreamina.windowsInstall": "Windows 暂请在 WSL 或手动安装即梦 CLI（curl -fsSL https://jimeng.jianying.com/cli | bash）。",
    "dreamina.installTimeout": "安装超时，请稍后重试或终端手动安装。",
    "dreamina.installFailed": "安装失败：{{message}}",
    "dreamina.installComplete": "即梦 CLI 安装完成。",
    "dreamina.installIncomplete": "安装未完成：{{message}}",
    "tasks.trackingLost": "本地任务追踪已丢失（可能因并发过高被清理）。该任务可能已在供应商侧完成——请稍后重试或在供应商后台查看。",
    "tasks.unknown": "未知任务：该任务不在本地待办缓存中（可能从未受理或 id 有误）。",
    "tasks.unrecognizedStatus": "上游返回了无法识别的任务状态：「{{status}}」。连续查询 {{polls}} 次、持续 {{seconds}} 秒都是这个状态，Nomi 按失败处理。该任务也可能仍在供应商侧运行——请到供应商后台核对。",
    "tasks.pollTimedOut": "等待生成结果超时（已等 {{seconds}} 秒，最后状态：{{status}}）。任务可能仍在供应商侧运行——请到供应商后台核对，或稍后重新拉取结果。",
    "tasks.pollFailed": "连续 {{seconds}} 秒查询生成结果失败（最后状态：{{status}}）。任务可能仍在供应商侧运行——请到供应商后台核对，或稍后重新拉取结果。",
    // ⚠️ 长度纪律：错误卡大标题走 classifyError.truncateLine，**超 100 字会被截尾**（那正是
    // 「该怎么办」那半句）。这两条 key 因此写得短，完整上下文留在 raw / 上游原话里。
    "tasks.noQueryOperation": "这个模型没有配置「查询结果」接口，而本次创建也没有返回任何产物——没有第二次查询可发，已按失败处理。请检查该模型的接入配置。",
    "outbound.fakeIpBlocked": "取片被安全策略拦下：{{host}} 解析到 {{address}}（RFC 2544 段，本地代理 fake-ip 常用它做合成地址），Nomi 无法确认这是代理而不是内网，于是拒绝了下载。**已付费的任务没有丢**，上游多半已经生成好了——请到「模型设置 → 网络」确认本地代理已开启，再用「重新拉取」免费取回，不用重新生成。",
    "outbound.privateAddress": "取片被安全策略拦下：{{host}} 解析到内网地址 {{address}}，Nomi 不会向内网下载产物（防止被诱导去探测你的路由器/NAS）。已付费的任务没有丢，修好 DNS 或代理后可用「重新拉取」免费取回。",
    "outbound.privateHost": "这个地址指向本机或内网（{{host}}），Nomi 不会从这里下载产物。若这是你自己的本地生成后端，请在模型设置里把它配置成供应商，而不是直接填链接。",
    "outbound.unresolvable": "找不到 {{host}} 的服务器地址（DNS 没有返回任何结果）。请检查网络或代理是否正常，然后用「重新拉取」免费重试。",
    "outbound.submitFakeIpBlocked": "这次生成**没有发出去，也没有扣费**：{{host}} 解析到 {{address}}（RFC 2544 段，本地代理 fake-ip 常用它做合成地址），Nomi 无法确认这是代理而不是内网，于是在请求发出前就拦下了。请到「模型接入 → 网络」确认本地代理已开启（那一行会写「检测到本地代理」），然后重新生成。",
    "outbound.submitPrivateAddress": "这次生成**没有发出去，也没有扣费**：{{host}} 解析到内网地址 {{address}}，Nomi 不会把带着密钥的请求发往内网。请检查 DNS 或代理；如果这确实是你自己的服务，请在模型设置里把它的完整地址配成供应商接入地址。",
    "outbound.submitPrivateHost": "这次生成**没有发出去，也没有扣费**：接入地址指向本机或内网（{{host}}）。如果这是你自己的本地后端，请在「模型接入」里把它配置成供应商；链路本地/元数据地址（169.254.x）永远不会被放行。",
    "outbound.submitUnresolvable": "这次生成**没有发出去，也没有扣费**：找不到 {{host}} 的服务器地址（DNS 没有返回任何结果）。请检查网络或代理，然后重新生成。",
    "tasks.completedWithoutOutput": "供应商报告任务完成，但没有返回可用产物；已按失败处理。请检查该模型的结果接口。",
    "tasks.modelUnresolvable": "模型当前不可执行（已下架或凭证失效），无法续查该任务的结果；已按失败处理。请到供应商后台核对任务，或重新配置该模型。",
    "tasks.missingTaskId": "供应商没有返回任务编号，无法安全查询结果；已按失败处理。请检查该模型的创建接口。",
    "tasks.upstreamSaid": "（上游原话：{{detail}}）",
    "deconstruct.spendDeclined": "这次拆解没有经过付费确认，一次请求都没有发出。",
    "deconstruct.noTranscribeModel": "对白没取到：这台机器上还没有可用的转写模型。去「接入模型」启用一个后重试；画面那半仍然拆好了。",
    "textTask.imagesUnreadable": "参考图都读不出来（{{count}} 张），没法让模型看图作答。请检查素材是否还在项目里。",
    "vendor.apimartOmni.imageUrlsArray": "APIMart Omni 参考图必须是图片数组。",
    "vendor.apimartOmni.imageCount": "APIMart Omni 参考图只支持 1 或 3 张。",
    "vendor.apimartOmni.generationType": "APIMart Omni 使用参考图时必须声明 reference 模式。",
    "vendor.kieGptImage25.ratioOneKOnly": "GPT Image 2.5 的 {{ratio}} 画幅只支持 1K，请把清晰度调回 1K 或换一个画幅。",
    "updater.devUnavailable": "开发模式下不可用，请在安装版中检查更新",
    "agent.confirmTimeout": "工具确认超时（长时间无响应，已自动跳过）",
    "agent.sessionCancelled": "会话已取消",
    "agent.processInterrupted": "上一次 Agent 进程在本轮完成前结束了。",
    "agent.provenanceConfirmation": "这段上下文来自未经验证的来源（{{sources}}），未经你确认不能直接执行{{action}}操作。",
    "integration.discoveryMissingBaseUrl": "无法探测模型：缺少中转站地址。请填写 base URL，并可手动填写 model ID。",
    "integration.discoveryMissingCredential": "无法探测模型：Nomi 没有找到已保存的密钥。请打开安全凭据页保存 key，或手动填写 model ID。",
    "integration.discoveryUnsupported": "中转站没有可用的 /models 接口，无法自动读取模型清单。请直接手动填写 model ID 后再次提交。",
    "integration.discoveryAuthFailed": "中转站拒绝了已保存的密钥。请回到安全凭据页重新保存 key，或手动填写 model ID。",
    "integration.discoveryFailed": "自动读取模型清单失败（{{reason}}）。请检查 base URL 后重试，也可以手动填写 model ID。",
    "integration.discoveryPlainText": "未能从模型清单识别类型，已按纯文本模型接入；如果它不是文本模型，请手动改类型。",
    // MCP URL 模式 elicitation 的凭据页文案（spec 2025-11-25 §URL Mode：密钥必须走页面、不得走 form）。
    "integration.credentialPage.title": "把 API 密钥交给 Nomi",
    "integration.credentialPage.lede": "只有这台电脑上的 Nomi 会看到你输入的密钥：它加密存在本机，不会经过 AI 助手、不会进模型上下文、不会写进日志。",
    "integration.credentialPage.providerLabel": "供应商",
    "integration.credentialPage.baseUrlLabel": "接口地址",
    "integration.credentialPage.keyLabel": "API 密钥",
    "integration.credentialPage.keyPlaceholder": "粘贴供应商给你的 key",
    "integration.credentialPage.keyRequired": "请先填写密钥。",
    "integration.credentialPage.test": "测试连接",
    "integration.credentialPage.testing": "正在连接…",
    "integration.credentialPage.testOk": "连上了，读到 {{count}} 个模型。",
    "integration.credentialPage.testFailed": "测试失败：{{reason}}",
    "integration.credentialPage.save": "保存并关闭",
    "integration.credentialPage.saving": "正在保存…",
    "integration.credentialPage.saved": "已保存。可以关掉这个页面，回你的 AI 助手继续。",
    "integration.credentialPage.saveFailed": "保存失败：{{reason}}",
    "integration.credentialPage.expired": "这个链接已失效（一次性、10 分钟有效）。回到 AI 助手重新发起一次接入即可。",
    "experience.untitled": "未命名经验",
    "browser.promptCategory.image": "图片提示词",
    "browser.promptCategory.video": "视频提示词",
    "export.missingWebmInput": "导出失败：缺少 WebM 输入数据",
    "export.missingProjectId": "导出失败：缺少项目 ID",
    "export.projectNotFound": "导出失败：找不到项目",
    "export.reveal.missingProjectId": "打开导出位置失败：缺少项目 ID",
    "export.reveal.missingPath": "打开导出位置失败：缺少导出文件路径",
    "export.reveal.outsideExports": "打开导出位置失败：只能打开当前项目 exports 文件夹内的文件",
    "export.reveal.fileMissing": "打开导出位置失败：导出文件不存在",
    "export.codecMissing": "导出失败：MP4 编码组件缺失，请重新安装 Nomi。你不需要单独安装 FFmpeg。",
    "export.inputMissing": "导出失败：输入视频不存在",
    "export.inputEmpty": "导出失败：输入视频为空",
    "export.detail": "导出失败：{{detail}}",
    "export.mp4NotProduced": "导出失败：MP4 文件未生成",
    "export.mp4Empty": "导出失败：MP4 文件为空",
    "production.reconcile.noTaskId": "供应商任务标识尚未收到，不能自动对账",
    "production.export.mustBeRelative": "导出必须返回项目目录内的相对路径",
    "production.export.escapesProject": "导出路径不能离开项目目录",
    "production.export.fileMissing": "导出文件不存在",
    "production.export.notAFile": "导出结果不是文件",
    "production.resume.noTaskId": "尚未收到供应商任务标识，不能自动恢复；请保持暂停并联系供应商核对",
    "production.approve.roughCutFirst": "请先完成粗剪审看，再单独批准导出",
    "dubbing.diskWriteFailed": "配音生成失败：音频落盘异常",
    "production.generationNoAdoptedShots": "生成阶段没有已采纳的镜头",
    "production.generationMissingCanvasNode": "生成镜头缺少画布节点：{jobId}",
    "production.generationMissingArtifact": "生成镜头缺少已落地产物：{{jobId}}",
    "dubbing.noText": "配音生成失败：没有台词文本",
    "dubbing.noVoice": "配音生成失败：未选择音色",
    "dubbing.networkError": "配音生成失败（{{vendor}} 网络错误）：{{detail}}",
    "dubbing.httpError": "配音生成失败（{{vendor}} HTTP {{status}}）：{{detail}}",
    "dubbing.emptyAudio": "配音生成失败：供应商返回空音频",
    "transcribe.noAudio": "转写失败：未提供音频（请先连接或上传一个音频）",
    "transcribe.networkError": "转写失败（{{vendor}} 网络错误）：{{detail}}",
    "transcribe.httpError": "转写失败（{{vendor}} HTTP {{status}}）：{{detail}}",
    "transcribe.noText": "转写失败：供应商未返回文本",
    "transcribe.unreachable": "转写失败：音频地址无法访问",
    // 本地转写（离线 whisper sidecar）。每一条都要说清「哪一步、为什么」，
    // 并由 UI 配一个「改用云端」出口——不许任何一条在代码里自动切云端（P1：不留静默兜底）。
    "localSpeech.unsupported-platform": "这台机器不支持本地转写（{{detail}}）。改用云端转写，或换一台 Mac（Apple 芯片/Intel）或 64 位 Windows。",
    "localSpeech.download-failed": "本地转写引擎没下载成功：{{detail}}。检查网络后重试，或改用云端转写。",
    "localSpeech.checksum-mismatch": "下载到的文件校验不通过（{{detail}}），已删除。这通常是网络中间层改写了文件——换个网络重试，或改用云端转写。",
    "localSpeech.disk-full": "磁盘空间不够，本地转写的模型没能落盘（{{detail}}）。腾出空间后重试，或改用云端转写。",
    "localSpeech.extract-failed": "本地转写引擎解包失败：{{detail}}。重试一次，或改用云端转写。",
    "localSpeech.engine-start-failed": "本地转写引擎起不来：{{detail}}。重试一次，或改用云端转写。",
    "localSpeech.chunk-failed": "本地转写第 {{detail}} 段失败（已重试一次）。重试整条，或改用云端转写。",
    "localSpeech.empty-result": "本地转写跑完了但一个字都没出（{{detail}}）。这段音频可能只有音乐或环境声；要确认的话改用云端转写对一遍。",
    "localSpeech.audio-unreadable": "读不出要转写的音频：{{detail}}。",
    "localSpeech.cancelled": "本地转写已取消（{{detail}}）。",
    "localSpeech.noGpuNotice": "这台机器没有 GPU 加速，本地转写预计要 {{minutes}} 分钟左右。",
    "localSpeech.progressDownload": "首次使用本地转写，正在下载引擎与模型 {{done}}/{{total}} MB（仅此一次）",
    "localSpeech.progressChunk": "本地转写第 {{index}}/{{count}} 段（{{done}}/{{total}} 秒）",
    "common.noDetail": "(无详情)",
    "syncAudio.missingDeclaredData": "配音生成失败：供应商未返回声明的音频数据",
    "syncAudio.invalidHex": "配音生成失败：供应商返回无效的十六进制音频",
    "syncAudio.invalidBase64": "配音生成失败：供应商返回无效的 Base64 音频",
    "syncAudio.invalidJson": "配音生成失败：供应商返回无效的 JSON 音频响应",
    "syncAudio.empty": "配音生成失败：供应商返回空音频",
    "browserMedia.typeMismatch": "网页返回的媒体类型不匹配（{{type}}）",
    "browserMedia.claimedButUnreadable": "网页响应头声称是媒体，但内容无法识别（{{type}}）",
    "browserMedia.notMedia": "网页返回的不是图片或视频（{{type}}）",
    "browserMedia.unrecognized": "网页返回的不是可识别的图片或视频",
    "browserMedia.downloadFailed": "网页素材下载失败（HTTP {{status}}）",
    "browserMedia.promptImageTooLarge": "图片过大，无法用于提示词提取（最大 16 MB）",
    "minimaxH3.mixedReferences": "MiniMax H3 请求参数冲突：首尾帧与参考素材不能同时使用，请只保留一组输入。",
    "assetUpload.missingPutHeaders": "上传参考素材失败：供应商没有按约定返回上传所需的协议头（期望路径 {{path}}）。稍后重试；一直这样就是供应商改了上传接口。",
    "assetUpload.headerNotString": "上传参考素材失败：供应商返回的上传协议头 {{name}} 不是文本，无法按原样发送。",
    "modelConstraints.referenceTotal": "参考素材总数最多 {{max}} 个（图片、视频和音频合计）。",
    "modelConstraints.parameterCombination": "当前参数组合不支持 {{parameter}}，请重新选择。",
    "minimaxH3.audioOnly": "MiniMax H3 多模态参考中音频不能单独输入，请至少提供参考图或参考视频。",
    "comfyWorkflow.invalidJson": "不是合法 JSON —— 请粘贴完整的 ComfyUI workflow.json 或 workflow_api.json。",
    "comfyWorkflow.invalidShape": "workflow 格式不对（应是节点对象）。",
    "comfyWorkflow.uiFormat": "这是 ComfyUI 保存的界面工作流，需要连接当前 ComfyUI 才能自动转换；启动后重试，也可以改用 Workflow → Export (API) 导出。",
    "comfyWorkflow.empty": "workflow 是空的。",
    "comfyWorkflow.missingClassType": "节点 {{id}} 缺 class_type —— 确认导出的是 API 格式（每个节点带 class_type + inputs）。",
    "comfyWorkflow.noOutput": "工作流没有可用的成品输出，请添加保存图片或视频的输出节点。",
    "comfyWorkflow.outputNodeMissing": "成品输出节点 #{{id}} 不存在，请重新选择输出节点。",
    "comfyWorkflow.createVideoNotOutput": "CreateVideo 不是成品输出，请选择下游保存视频的节点。",
    "comfyWorkflow.unsupportedOutput": "暂不支持 {{classType}} 的成品输出类型。",
    "comfyWorkflow.unknownOutput": "无法识别 {{classType}} 的成品类型，请明确指定输出类型。",
    "decompose.timeout": "拆解超时，请稍后重试",
    "decompose.missingImage": "缺少待拆解图片",
    "decompose.notConnected": "Replicate 未接入：请先在「模型设置」里填入 Replicate API Token",
    "decompose.missingToken": "Replicate 未填 API Token：请在「模型设置」里填入 r8_ 开头的 token",
    "decompose.submitFailed": "拆解提交失败",
    "decompose.failed": "拆解失败",
    "decompose.noLayers": "拆解未返回任何图层",
    "runway.seedanceBody": "Runway Seedance 2.5 请求体必须是 JSON 对象",
    "runway.seedanceMaxImages": "Runway Seedance 2.5 最多 {{count}} 张参考图",
    "runway.seedanceMaxVideos": "Runway Seedance 2.5 最多 {{count}} 个参考视频",
    "runway.seedanceMaxAudios": "Runway Seedance 2.5 最多 {{count}} 个参考音频",
    "runway.seedanceEmptyImage": "Runway Seedance 2.5 参考图不能为空",
    "runway.seedanceKeyframes": "Runway Seedance 2.5 首尾帧必须同时提供",
    "runway.videoBody": "Runway 视频请求体必须是 JSON 对象",
    "runway.imageBody": "Runway 图像请求体必须是 JSON 对象",
    "runway.gen4ReferenceRequired": "Runway Gen-4 Image Turbo 必须提供至少一张参考图",
    "runway.maxImageReferences": "Runway 图像模型最多 {{count}} 张参考图",
    "runway.audioBody": "Runway 音频请求体必须是 JSON 对象",
    "runway.maxAudioReferences": "Runway seed_audio 最多 {{count}} 个参考音频",
    "review.imageUndecodable": "图片无法解码或尺寸为 0",
    "review.duration": "时长 {{seconds}}s",
    "review.zeroDuration": "视频时长为 0",
    "review.blackRatio": "约 {{percent}}% 画面是黑的",
    "review.blackFrames": "黑帧占比 {{percent}}%",
    "review.silentAudio": "音轨几乎全程静音",
    "review.silenceRatio": "静音占比 {{percent}}%",
    "review.probeFailed": "媒体探测失败：{{detail}}",
    "customCall.timeout": "自定义调用脚本超时（{{seconds}}s）",
    "customCall.formDataEntry": "FormData 条目无效",
    "customCall.formDataBytes": "FormData 字段 {{name}} 的二进制内容无效",
    "customCall.formDataValue": "FormData 字段 {{name}} 的值无效",
    "customCall.saveFileUnavailable": "saveFile 在这里不可用（试跑不落盘）——先 return 一个 URL 或 dataURL 验证脚本能跑通",
    "customCall.noOutput": "自定义调用脚本没有返回产物（资产请 return URL / dataURL / 它们的数组；文本模型请 return { text: '…' }）",
    "catalog.vendorMissing": "供应商不存在：{{vendor}}",
    "catalog.modelMissing": "模型不存在：{{vendor}}/{{model}}",
    "customCall.previewFileTooLarge": "试跑 saveFile 收到的文件太大，不能在面板里拼 data URL；请直接保存后在真实任务里验证",
    "customCall.emptyScript": "脚本为空——先写点内容或让 AI 生成",
  },
  en: {
    "sourceTask.missing": "Connect a compatible generated video or enter its source task ID. No generation was submitted.",
    "agent.legacySummary": "Legacy summary: ",
    "agent.legacyUnverifiedTool": "Legacy tool outcome is unverified.",
    "credential.invalid": "Key validation failed. Check the key and permissions, then retry.",
    "credential.revalidationUnavailable": "Key saved but not verified. Reconnect and retry to verify automatically.",
    "credential.validationUnavailable": "Cannot validate the key. Check the API address and network, then retry.",
    "credential.previousKept": "Your previous key and connection are unchanged.",
    "credential.changed": "The connection changed during validation. Save again. The previous key was not overwritten.",
    "workspace.selectTitle": "Choose a Nomi project folder",
    "workspace.openButton": "Open folder",
    "workspace.invalidFolder": "No valid folder was selected",
    "workspace.protectedFolder": "“{{path}}” is your home folder or a protected system folder and cannot be used as a Nomi project folder. Choose or create an empty folder instead.",
    "workspace.initializeTitle": "Initialize this Nomi project folder?",
    "workspace.initializeDetail": "Nomi will create .nomi/ here and save generated images and videos in assets/ and exports/.\n\n{{path}}",
    "common.cancel": "Cancel",
    "common.initialize": "Initialize",
    "common.unknownError": "Unknown error",
    "dreamina.reusedLogin": "Dreamina reused the existing local sign-in. No new QR scan is needed; Nomi will refresh the current status.",
    "dreamina.loginStartFailed": "Could not start Dreamina sign-in: {{message}}",
    "dreamina.missingDeviceCode": "Missing device_code",
    "dreamina.loginSuccess": "Signed in",
    "dreamina.waiting": "Waiting for authorization…",
    "dreamina.loginFailed": "Sign-in failed",
    "dreamina.installed": "Dreamina CLI is installed",
    "dreamina.windowsInstall": "On Windows, install Dreamina CLI in WSL or manually with: curl -fsSL https://jimeng.jianying.com/cli | bash",
    "dreamina.installTimeout": "Installation timed out. Try again later or install it manually in a terminal.",
    "dreamina.installFailed": "Installation failed: {{message}}",
    "dreamina.installComplete": "Dreamina CLI installation completed.",
    "dreamina.installIncomplete": "Installation did not complete: {{message}}",
    "tasks.trackingLost": "Local task tracking was lost, possibly because too many tasks were running. The provider may still have completed it; try again later or check the provider dashboard.",
    "tasks.unknown": "Unknown task: it is not in the local pending-task cache. It may never have been accepted, or its ID may be incorrect.",
    "tasks.unrecognizedStatus": "The provider returned an unrecognized task status: “{{status}}”. It stayed that way for {{polls}} polls over {{seconds}}s, so Nomi is treating the task as failed. It may still be running on the provider side — check your provider dashboard.",
    "tasks.pollTimedOut": "Timed out waiting for the result (waited {{seconds}}s, last status: {{status}}). The task may still be running on the provider side — check your provider dashboard or fetch the result again later.",
    "tasks.pollFailed": "Failed to fetch the generation result for {{seconds}}s in a row (last status: {{status}}). The task may still be running on the provider side — check your provider dashboard or fetch the result again later.",
    "tasks.noQueryOperation": "This model has no result-query operation and the create call returned nothing. Check its setup.",
    "outbound.fakeIpBlocked": "The download was blocked by Nomi's own network policy: {{host}} resolved to {{address}} (the RFC 2544 range that local fake-IP proxies use for synthetic addresses). Nomi could not confirm a proxy is running, so it refused the download. **Your paid task is not lost** - confirm your local proxy under Model settings > Network, then use \"Re-fetch result\" to retrieve it for free. Do not regenerate.",
    "outbound.privateAddress": "The download was blocked by Nomi's own network policy: {{host}} resolved to the private address {{address}}, and Nomi never downloads results from private networks. Your paid task is not lost - fix DNS or the proxy, then use \"Re-fetch result\" to retrieve it for free.",
    "outbound.privateHost": "This address points at your own machine or private network ({{host}}), so Nomi will not download results from it. If it is your own local backend, configure it as a provider in model settings instead of pasting the link.",
    "outbound.unresolvable": "No server address found for {{host}} (DNS returned nothing). Check your network or proxy, then use \"Re-fetch result\" to retry for free.",
    "outbound.submitFakeIpBlocked": "This generation **was never sent, and nothing was charged**: {{host}} resolved to {{address}} (the RFC 2544 range local fake-IP proxies use for synthetic addresses), and Nomi could not confirm a proxy is running, so it stopped the request before it left your machine. Confirm your local proxy under Model Access > Network (that row reads \"Local proxy detected\"), then generate again.",
    "outbound.submitPrivateAddress": "This generation **was never sent, and nothing was charged**: {{host}} resolved to the private address {{address}}, and Nomi never sends a credential-bearing request into a private network. Check DNS or your proxy; if this really is your own service, configure its full address as a provider endpoint in model settings.",
    "outbound.submitPrivateHost": "This generation **was never sent, and nothing was charged**: the endpoint points at your own machine or private network ({{host}}). If it is your own local backend, configure it as a provider under Model Access. Link-local / metadata addresses (169.254.x) are never allowed.",
    "outbound.submitUnresolvable": "This generation **was never sent, and nothing was charged**: no server address was found for {{host}} (DNS returned nothing). Check your network or proxy, then generate again.",
    "tasks.completedWithoutOutput": "The provider reported completion but returned no usable output. Check this model's result endpoint.",
    "tasks.modelUnresolvable": "The model is no longer executable (removed or its credential is invalid), so the task result cannot be fetched; treated as failed. Check your provider dashboard or reconfigure the model.",
    "tasks.missingTaskId": "The provider did not return a task ID, so Nomi cannot safely query the result. Check this model's create endpoint.",
    "tasks.upstreamSaid": " (Upstream said: {{detail}})",
    "deconstruct.spendDeclined": "This deconstruction was never confirmed for spending, so no request was sent.",
    "deconstruct.noTranscribeModel": "Dialogue was skipped: no transcription model is available on this machine. Enable one under model access and retry; the visual half is still done.",
    "textTask.imagesUnreadable": "None of the {{count}} reference image(s) could be read, so the model cannot answer from the image. Check that the assets are still in the project.",
    "vendor.apimartOmni.imageUrlsArray": "APIMart Omni reference images must be an image array.",
    "vendor.apimartOmni.imageCount": "APIMart Omni supports exactly 1 or 3 reference images.",
    "vendor.apimartOmni.generationType": "APIMart Omni requires reference mode when reference images are used.",
    "vendor.kieGptImage25.ratioOneKOnly": "GPT Image 2.5 supports 1K only for the {{ratio}} aspect ratio. Set resolution back to 1K, or pick another aspect ratio.",
    "updater.devUnavailable": "Updates are unavailable in development mode. Check for updates in an installed build.",
    "agent.confirmTimeout": "Tool confirmation timed out and the action was skipped",
    "agent.sessionCancelled": "The session was cancelled",
    "agent.processInterrupted": "The previous Agent process ended before this turn completed.",
    "agent.provenanceConfirmation": "This context came from unverified sources ({{sources}}); your explicit confirmation is required before this {{action}} action.",
    "integration.discoveryMissingBaseUrl": "Model discovery needs a relay URL. Enter a base URL, or enter a model ID manually.",
    "integration.discoveryMissingCredential": "Model discovery could not find a saved key. Save it in Nomi's secure page, or enter a model ID manually.",
    "integration.discoveryUnsupported": "This relay has no usable /models route, so Nomi cannot read its model list. Enter model IDs manually and submit again.",
    "integration.discoveryAuthFailed": "The relay rejected the saved key. Save it again in Nomi's secure page, or enter a model ID manually.",
    "integration.discoveryFailed": "Model-list discovery failed ({{reason}}). Check the base URL and retry, or enter a model ID manually.",
    "integration.discoveryPlainText": "The model list did not identify a capability, so this was added as plain text. Change its type if needed.",
    "integration.credentialPage.title": "Give Nomi the API key",
    "integration.credentialPage.lede": "Only Nomi on this computer sees what you type: the key is encrypted locally and never reaches your AI assistant, the model context, or any log.",
    "integration.credentialPage.providerLabel": "Provider",
    "integration.credentialPage.baseUrlLabel": "API base URL",
    "integration.credentialPage.keyLabel": "API key",
    "integration.credentialPage.keyPlaceholder": "Paste the key your provider gave you",
    "integration.credentialPage.keyRequired": "Enter the key first.",
    "integration.credentialPage.test": "Test connection",
    "integration.credentialPage.testing": "Connecting\u2026",
    "integration.credentialPage.testOk": "Connected. Found {{count}} models.",
    "integration.credentialPage.testFailed": "Test failed: {{reason}}",
    "integration.credentialPage.save": "Save and close",
    "integration.credentialPage.saving": "Saving\u2026",
    "integration.credentialPage.saved": "Saved. You can close this page and go back to your AI assistant.",
    "integration.credentialPage.saveFailed": "Could not save: {{reason}}",
    "integration.credentialPage.expired": "This link is no longer valid (single use, 10 minutes). Ask your AI assistant to start the connection again.",
    "experience.untitled": "Untitled experience",
    "browser.promptCategory.image": "Image prompts",
    "browser.promptCategory.video": "Video prompts",
    "export.missingWebmInput": "Export failed: missing WebM input data",
    "export.missingProjectId": "Export failed: missing project ID",
    "export.projectNotFound": "Export failed: project not found",
    "export.reveal.missingProjectId": "Could not open export location: missing project ID",
    "export.reveal.missingPath": "Could not open export location: missing export file path",
    "export.reveal.outsideExports": "Could not open export location: only files inside this project's exports folder can be opened",
    "export.reveal.fileMissing": "Could not open export location: the export file does not exist",
    "export.codecMissing": "Export failed: the MP4 encoder is missing. Reinstall Nomi — you do not need to install FFmpeg separately.",
    "export.inputMissing": "Export failed: the input video does not exist",
    "export.inputEmpty": "Export failed: the input video is empty",
    "export.detail": "Export failed: {{detail}}",
    "export.mp4NotProduced": "Export failed: no MP4 file was produced",
    "export.mp4Empty": "Export failed: the MP4 file is empty",
    "production.reconcile.noTaskId": "The provider task ID has not arrived yet, so automatic reconciliation is not possible",
    "production.export.mustBeRelative": "Export must return a path relative to the project directory",
    "production.export.escapesProject": "The export path cannot leave the project directory",
    "production.export.fileMissing": "The export file does not exist",
    "production.export.notAFile": "The export result is not a file",
    "production.resume.noTaskId": "The provider task ID has not arrived yet, so automatic resume is not possible. Keep it paused and check with the provider.",
    "production.approve.roughCutFirst": "Finish reviewing the rough cut first, then approve the export separately",
    "dubbing.diskWriteFailed": "Voiceover failed: could not write the audio to disk",
    "production.generationNoAdoptedShots": "No adopted shots are available for generation",
    "production.generationMissingCanvasNode": "Generated shot is missing a canvas node: {jobId}",
    "production.generationMissingArtifact": "Generated shot is missing a landed artifact: {{jobId}}",
    "dubbing.noText": "Voiceover failed: no dialogue text",
    "dubbing.noVoice": "Voiceover failed: no voice selected",
    "dubbing.networkError": "Voiceover failed ({{vendor}} network error): {{detail}}",
    "dubbing.httpError": "Voiceover failed ({{vendor}} HTTP {{status}}): {{detail}}",
    "dubbing.emptyAudio": "Voiceover failed: the provider returned empty audio",
    "transcribe.noAudio": "Transcription failed: no audio provided (connect or upload an audio clip first)",
    "transcribe.networkError": "Transcription failed ({{vendor}} network error): {{detail}}",
    "transcribe.httpError": "Transcription failed ({{vendor}} HTTP {{status}}): {{detail}}",
    "transcribe.noText": "Transcription failed: the provider returned no text",
    "transcribe.unreachable": "Transcription failed: the audio URL is unreachable",
    "localSpeech.unsupported-platform": "This machine cannot run local transcription ({{detail}}). Use cloud transcription instead, or switch to a Mac (Apple silicon or Intel) or 64-bit Windows.",
    "localSpeech.download-failed": "The local transcription engine failed to download: {{detail}}. Check your connection and retry, or use cloud transcription.",
    "localSpeech.checksum-mismatch": "A downloaded file failed verification ({{detail}}) and was deleted. This usually means something on the network rewrote it \u2014 try another network, or use cloud transcription.",
    "localSpeech.disk-full": "Not enough disk space to store the local transcription model ({{detail}}). Free up space and retry, or use cloud transcription.",
    "localSpeech.extract-failed": "Unpacking the local transcription engine failed: {{detail}}. Retry once, or use cloud transcription.",
    "localSpeech.engine-start-failed": "The local transcription engine would not start: {{detail}}. Retry once, or use cloud transcription.",
    "localSpeech.chunk-failed": "Local transcription failed on chunk {{detail}} (already retried once). Retry the whole clip, or use cloud transcription.",
    "localSpeech.empty-result": "Local transcription finished but produced no text ({{detail}}). This clip may only contain music or ambience; run cloud transcription to double-check.",
    "localSpeech.audio-unreadable": "Could not read the audio to transcribe: {{detail}}.",
    "localSpeech.cancelled": "Local transcription was cancelled ({{detail}}).",
    "localSpeech.noGpuNotice": "This machine has no GPU acceleration; local transcription should take about {{minutes}} minutes.",
    "localSpeech.progressDownload": "First local transcription \u2014 downloading the engine and model, {{done}}/{{total}} MB (one time only)",
    "localSpeech.progressChunk": "Local transcription, chunk {{index}}/{{count}} ({{done}}/{{total}}s)",
    "common.noDetail": "(no details)",
    "syncAudio.missingDeclaredData": "Voiceover failed: the provider returned no declared audio data",
    "syncAudio.invalidHex": "Voiceover failed: the provider returned invalid hexadecimal audio",
    "syncAudio.invalidBase64": "Voiceover failed: the provider returned invalid Base64 audio",
    "syncAudio.invalidJson": "Voiceover failed: the provider returned an invalid JSON audio response",
    "syncAudio.empty": "Voiceover failed: the provider returned empty audio",
    "browserMedia.typeMismatch": "The web page returned a different media type ({{type}})",
    "browserMedia.claimedButUnreadable": "The web response claims to be media, but its content is unreadable ({{type}})",
    "browserMedia.notMedia": "The web page returned neither an image nor a video ({{type}})",
    "browserMedia.unrecognized": "The web page returned no recognizable image or video",
    "browserMedia.downloadFailed": "Could not download web media (HTTP {{status}})",
    "browserMedia.promptImageTooLarge": "The image is too large for prompt extraction (maximum 16 MB)",
    "minimaxH3.mixedReferences": "MiniMax H3 cannot use first/last frames and reference media together. Keep only one input group.",
    "assetUpload.missingPutHeaders": "Could not upload the reference asset: the provider did not return the upload headers it promised (expected at {{path}}). Retry; if it keeps happening the provider changed its upload API.",
    "assetUpload.headerNotString": "Could not upload the reference asset: the provider returned upload header {{name}} as something other than text, so it cannot be sent as-is.",
    "modelConstraints.referenceTotal": "Use at most {{max}} references in total (images, videos and audio combined).",
    "modelConstraints.parameterCombination": "The current parameter combination does not support {{parameter}}. Choose another value.",
    "minimaxH3.audioOnly": "MiniMax H3 cannot use audio as the only multimodal reference. Add a reference image or video.",
    "comfyWorkflow.invalidJson": "Invalid JSON. Paste a complete ComfyUI workflow.json or workflow_api.json.",
    "comfyWorkflow.invalidShape": "Invalid workflow shape. It must be a node object.",
    "comfyWorkflow.uiFormat": "This is a ComfyUI interface workflow. Connect the current ComfyUI instance to convert it, or export it as Workflow → Export (API).",
    "comfyWorkflow.empty": "The workflow is empty.",
    "comfyWorkflow.missingClassType": "Node {{id}} is missing class_type. Make sure the export is API format with class_type and inputs on every node.",
    "comfyWorkflow.noOutput": "The workflow has no usable final output. Add an image or video save node.",
    "comfyWorkflow.outputNodeMissing": "Final output node #{{id}} does not exist. Select the output node again.",
    "comfyWorkflow.createVideoNotOutput": "CreateVideo is not a final output. Select a downstream video save node.",
    "comfyWorkflow.unsupportedOutput": "The final output type for {{classType}} is not supported yet.",
    "comfyWorkflow.unknownOutput": "The final output type for {{classType}} is unknown. Specify it explicitly.",
    "decompose.timeout": "Layer decomposition timed out. Try again later.",
    "decompose.missingImage": "No image was provided for layer decomposition.",
    "decompose.notConnected": "Replicate is not connected. Add a Replicate API token in Model settings first.",
    "decompose.missingToken": "No Replicate API token is configured. Add an r8_ token in Model settings.",
    "decompose.submitFailed": "Layer decomposition could not be submitted.",
    "decompose.failed": "Layer decomposition failed.",
    "decompose.noLayers": "Layer decomposition returned no layers.",
    "runway.seedanceBody": "The Runway Seedance 2.5 request body must be a JSON object",
    "runway.seedanceMaxImages": "Runway Seedance 2.5 allows at most {{count}} reference images",
    "runway.seedanceMaxVideos": "Runway Seedance 2.5 allows at most {{count}} reference videos",
    "runway.seedanceMaxAudios": "Runway Seedance 2.5 allows at most {{count}} reference audio files",
    "runway.seedanceEmptyImage": "Runway Seedance 2.5 requires a reference image",
    "runway.seedanceKeyframes": "Runway Seedance 2.5 requires both first and last frames",
    "runway.videoBody": "The Runway video request body must be a JSON object",
    "runway.imageBody": "The Runway image request body must be a JSON object",
    "runway.gen4ReferenceRequired": "Runway Gen-4 Image Turbo requires at least one reference image",
    "runway.maxImageReferences": "Runway image models allow at most {{count}} reference images",
    "runway.audioBody": "The Runway audio request body must be a JSON object",
    "runway.maxAudioReferences": "Runway seed_audio allows at most {{count}} reference audio files",
    "review.imageUndecodable": "The image could not be decoded or has zero dimensions",
    "review.duration": "Duration {{seconds}}s",
    "review.zeroDuration": "The video duration is zero",
    "review.blackRatio": "About {{percent}}% of the frames are black",
    "review.blackFrames": "Black frames: {{percent}}%",
    "review.silentAudio": "The audio track is almost silent throughout",
    "review.silenceRatio": "Silent audio: {{percent}}%",
    "review.probeFailed": "Media inspection failed: {{detail}}",
    "customCall.timeout": "Custom call script timed out ({{seconds}}s)",
    "customCall.formDataEntry": "Invalid FormData entry",
    "customCall.formDataBytes": "Invalid binary content in FormData field {{name}}",
    "customCall.formDataValue": "Invalid value in FormData field {{name}}",
    "customCall.saveFileUnavailable": "saveFile is unavailable here because a test run does not write files. Return a URL or data URL to validate the script.",
    "customCall.noOutput": "The custom call script returned no output. Assets must return a URL, data URL, or array; text models must return { text: '…' }.",
    "catalog.vendorMissing": "Vendor does not exist: {{vendor}}",
    "catalog.modelMissing": "Model does not exist: {{vendor}}/{{model}}",
    "customCall.previewFileTooLarge": "The test run received a file too large to preview as a data URL. Save it directly and verify it in a real task.",
    "customCall.emptyScript": "The script is empty. Write some code or ask AI to generate it first.",
  },
} as const;

export type DesktopTranslationKey = keyof (typeof translations)["zh-CN"];

export function desktopT(key: DesktopTranslationKey, values: Record<string, string | number> = {}, locale: DesktopLocale = getDesktopLocale()): string {
  let text: string = translations[locale][key];
  for (const [name, value] of Object.entries(values)) {
    text = text.replace(new RegExp(`\\{\\{${name}\\}\\}`, 'g'), String(value));
  }
  return text;
}
