import React from 'react'
import type { LabState } from '../../labScreen'
import { ProcessFeedbackStage, ProcessFeedbackFxStage, ProcessFeedbackImportStage } from '../processFeedbackLabKit'

const SOURCE = 'docs/plan/2026-09-08-process-feedback-c1.md · C0/C1/C2'
const FX_SOURCE = 'docs/plan/2026-09-09-process-feedback-imgfx.md · §5'
const IMPORT_SOURCE = 'docs/plan/2026-09-14-import-progress-reveal.md · 验收门'
export const PROCESS_FEEDBACK_STATES: readonly LabState[] = [
  {
    id: 'pf-fx-organic',
    name: '生成动效 · 有机像素对照',
    source: FX_SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackFxStage preset="pixels-organic" />,
  },
  {
    id: 'pf-fx-generating',
    name: '生成动效 · 等待',
    source: FX_SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackFxStage />,
  },
  {
    id: 'pf-fx-preview-reveal',
    name: '生成动效 · 真帧揭示',
    source: FX_SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackFxStage transition="preview" />,
  },
  {
    id: 'pf-fx-final-reveal',
    name: '生成动效 · 最终揭示',
    source: FX_SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackFxStage transition="saved" />,
  },
  {
    id: 'pf-fx-done-clean',
    name: '生成动效 · 完成零遮挡',
    source: FX_SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackFxStage transition="saved" />,
  },
  {
    id: 'pf-fx-reduced',
    name: '生成动效 · 减弱动态',
    source: FX_SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackFxStage reduced />,
  },
  {
    id: 'pf-import-progress',
    name: '导入中 · 42%（进度驱动的渐显）',
    source: IMPORT_SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackImportStage ratio={0.42} />,
  },
  {
    id: 'pf-import-reduced',
    name: '导入中 · 无 GPU 兜底（扫光带，无进度线）',
    source: IMPORT_SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackImportStage ratio={0.42} reduced />,
  },
  {
    id: 'pf-image-queued',
    name: '图片 · 排队',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="image" stage="queued" />,
  },
  {
    id: 'pf-image-submitting',
    name: '图片 · 提交',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="image" stage="requesting" />,
  },
  {
    id: 'pf-image-generating',
    name: '图片 · 生成中',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="image" stage="generating" />,
  },
  {
    id: 'pf-image-finalizing',
    name: '图片 · 落盘',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="image" stage="finalizing" />,
  },
  {
    id: 'pf-image-failed',
    name: '图片 · 失败',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="image" stage="failed" />,
  },
  {
    id: 'pf-video-queued',
    name: '视频 · 排队',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="video" stage="queued" />,
  },
  {
    id: 'pf-video-submitting',
    name: '视频 · 提交',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="video" stage="requesting" />,
  },
  {
    id: 'pf-video-generating',
    name: '视频 · 生成中',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="video" stage="generating" />,
  },
  {
    id: 'pf-video-finalizing',
    name: '视频 · 落盘',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="video" stage="finalizing" />,
  },
  {
    id: 'pf-video-failed',
    name: '视频 · 失败',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="video" stage="failed" />,
  },
  {
    id: 'pf-audio-queued',
    name: '音频 · 排队',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="audio" stage="queued" />,
  },
  {
    id: 'pf-audio-submitting',
    name: '音频 · 提交',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="audio" stage="requesting" />,
  },
  {
    id: 'pf-audio-generating',
    name: '音频 · 生成中',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="audio" stage="generating" />,
  },
  {
    id: 'pf-audio-finalizing',
    name: '音频 · 落盘',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="audio" stage="finalizing" />,
  },
  {
    id: 'pf-audio-failed',
    name: '音频 · 失败',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="audio" stage="failed" />,
  },
  {
    id: 'pf-preview',
    name: '真实预览帧',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="image" stage="comfyui-node" preview percent={60} />,
  },
  {
    id: 'pf-late',
    name: '软超时仍运行',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="video" stage="still-generating" />,
  },
  {
    id: 'pf-zoom-60',
    name: '60% 缩放可读',
    source: SOURCE,
    coverage: 'shell',
    render: () => <ProcessFeedbackStage kind="image" stage="generating" zoom={0.6} />,
  },
  {
    id: 'pf-preview-dark',
    name: '暗色真实预览',
    source: SOURCE,
    coverage: 'shell',
    scheme: 'dark',
    render: () => <ProcessFeedbackStage kind="image" stage="comfyui-node" preview percent={60} />,
  },
]
