// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// Replicate 分片：避免默认值主表超过 800 行文件体积门岗。运行时由主表透明合并。
export const REPLICATE_ARCHETYPE_WIRE_DEFAULTS: Record<string, Record<string, Record<string, Record<string, unknown>>>> = {
  "replicate-flux-schnell": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "1:1",
        "num_outputs": 1,
        "num_inference_steps": 4,
        "output_format": "webp",
        "output_quality": 80,
        "disable_safety_checker": false,
        "go_fast": true,
        "megapixels": "1"
      }
    }
  },
  "replicate-flux-kontext-pro": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "match_input_image",
        "output_format": "png",
        "safety_tolerance": 2,
        "prompt_upsampling": false
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "match_input_image",
        "output_format": "png",
        "safety_tolerance": 2,
        "prompt_upsampling": false
      }
    }
  },
  "replicate-qwen-image-edit": {
    "image_edit": {
      "*": {
        "aspect_ratio": "match_input_image",
        "go_fast": true,
        "output_format": "webp",
        "output_quality": 95,
        "disable_safety_checker": false
      }
    }
  },
  "replicate-nano-banana": {
    "text_to_image": {
      "*": {
        "aspect_ratio": "match_input_image",
        "output_format": "jpg"
      }
    },
    "image_edit": {
      "*": {
        "aspect_ratio": "match_input_image",
        "output_format": "jpg"
      }
    }
  },
  "replicate-minimax-video-01": {
    "text_to_video": {
      "*": {
        "prompt_optimizer": true
      }
    },
    "image_to_video": {
      "*": {
        "prompt_optimizer": true
      }
    }
  },
  "replicate-seedance-1-pro": {
    "text_to_video": {
      "*": {
        "duration": 5,
        "resolution": "1080p",
        "aspect_ratio": "16:9",
        "camera_fixed": false
      }
    },
    "image_to_video": {
      "*": {
        "duration": 5,
        "resolution": "1080p",
        "camera_fixed": false
      }
    }
  }
};
