// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// 档案模式桥接：主进程只据此校验 modeId/taskKind；完整输入能力仍以 renderer 档案为真相源。
export const ARCHETYPE_MODE_MANIFEST: Record<string, { defaultModeId: string; modes: Record<string, string> }> = {
  "seedance-2": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "first": "image_to_video",
      "firstlast": "image_to_video",
      "omni": "image_to_video"
    }
  },
  "seedance-2.5": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "first": "image_to_video",
      "firstlast": "image_to_video",
      "omni": "image_to_video"
    }
  },
  "minimax-h3": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "text_to_video",
      "ref": "text_to_video"
    }
  },
  "minimax-h3-max": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video"
    }
  },
  "happyhorse": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "text_to_video",
      "ref": "text_to_video",
      "edit": "text_to_video"
    }
  },
  "vidu-q3": {
    "defaultModeId": "ref",
    "modes": {
      "ref": "image_to_video"
    }
  },
  "kling-3.0-turbo": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video"
    }
  },
  "happyhorse-1.1": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video",
      "ref": "image_to_video"
    }
  },
  "grok-imagine-1.5-video": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video"
    }
  },
  "sora-2": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video"
    }
  },
  "veo-3.1": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "reference": "image_to_video",
      "frame": "image_to_video"
    }
  },
  "gemini-omni-1.1": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "firstlast": "image_to_video",
      "reference": "image_to_video"
    }
  },
  "runway-gen4.5": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video"
    }
  },
  "runway-gen4-turbo": {
    "defaultModeId": "i2v",
    "modes": {
      "i2v": "image_to_video"
    }
  },
  "kling-3.0": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video"
    }
  },
  "seedance-2-apimart": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video",
      "omni": "image_to_video",
      "firstlast": "image_to_video"
    }
  },
  "seedance-2.5-apimart": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "first": "image_to_video",
      "firstlast": "image_to_video",
      "omni": "image_to_video"
    }
  },
  "minimax-h3-apimart": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "first": "image_to_video",
      "firstlast": "image_to_video",
      "ref": "image_to_video"
    }
  },
  "wan-2.7": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video",
      "ref": "image_to_video"
    }
  },
  "wan-3.0": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "first": "image_to_video",
      "firstlast": "image_to_video",
      "ref": "image_to_video"
    }
  },
  "wan-3.0-apimart": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "first": "image_to_video",
      "firstlast": "image_to_video",
      "ref": "image_to_video"
    }
  },
  "hailuo-2.3": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video"
    }
  },
  "omni-flash-ext": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video"
    }
  },
  "minimax-h3-regeneration": {
    "defaultModeId": "regenerate",
    "modes": {
      "regenerate": "text_to_video"
    }
  },
  "volcengine-seedance-2": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "first": "image_to_video",
      "firstlast": "image_to_video",
      "omni": "image_to_video"
    }
  },
  "volcengine-seedance-2-5": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "first": "image_to_video",
      "firstlast": "image_to_video",
      "omni": "image_to_video"
    }
  },
  "dreamina-seedance-2": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video",
      "firstlast": "image_to_video",
      "multimodal": "image_to_video"
    }
  },
  "dreamina-multiframe": {
    "defaultModeId": "multiframe",
    "modes": {
      "multiframe": "image_to_video"
    }
  },
  "runninghub-seedance": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_video",
      "image": "image_to_video"
    }
  },
  "rh-veo-3.1": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_video",
      "image": "image_to_video"
    }
  },
  "rh-kling-3.0": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_video",
      "image": "image_to_video"
    }
  },
  "rh-wan-2.7": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_video",
      "image": "image_to_video"
    }
  },
  "rh-hailuo-2.3": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_video",
      "image": "image_to_video"
    }
  },
  "rh-sora-2": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_video",
      "image": "image_to_video"
    }
  },
  "agnes-video": {
    "defaultModeId": "t2v",
    "modes": {
      "t2v": "text_to_video",
      "i2v": "image_to_video",
      "keyframes": "image_to_video"
    }
  },
  "agnes-video-2.5": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_video",
      "keyframe": "image_to_video",
      "reference": "image_to_video"
    }
  },
  "agnes-video-2.5-flash": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_video",
      "keyframe": "image_to_video",
      "reference": "image_to_video"
    }
  },
  "minimax-music-3": {
    "defaultModeId": "music",
    "modes": {
      "music": "text_to_audio"
    }
  },
  "minimax-speech-2.8": {
    "defaultModeId": "speech",
    "modes": {
      "speech": "text_to_audio"
    }
  },
  "eleven-v3": {
    "defaultModeId": "speech",
    "modes": {
      "speech": "text_to_audio"
    }
  },
  "eleven-music-v2": {
    "defaultModeId": "music",
    "modes": {
      "music": "text_to_audio"
    }
  },
  "eleven-sfx-v2": {
    "defaultModeId": "sfx",
    "modes": {
      "sfx": "text_to_audio"
    }
  },
  "eleven-scribe-v2": {
    "defaultModeId": "transcribe",
    "modes": {
      "transcribe": "transcribe"
    }
  },
  "meshy-7": {
    "defaultModeId": "i2m",
    "modes": {
      "i2m": "image_to_3d"
    }
  },
  "runway-image-reference": {
    "defaultModeId": "i2i",
    "modes": {
      "i2i": "image_edit"
    }
  },
  "runway-image": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "i2i": "image_edit"
    }
  },
  "runway-audio": {
    "defaultModeId": "sfx",
    "modes": {
      "sfx": "text_to_audio",
      "speech": "text_to_audio"
    }
  },
  "gpt-image-2": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "i2i": "image_edit"
    }
  },
  "seedream": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "kie-seedream-5-pro": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "kie-seedream-5-lite": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "nano-banana-2": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "nano-banana-2-lite": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "nano-banana": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "flux-2-pro": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "qwen-image-3": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "qwen-image": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "imagen-4": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image"
    }
  },
  "z-image-turbo": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image"
    }
  },
  "seedream-5-pro": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "nomi-audio": {
    "defaultModeId": "speech",
    "modes": {
      "speech": "text_to_audio",
      "transcribe": "transcribe"
    }
  },
  "suno-v5.5": {
    "defaultModeId": "music",
    "modes": {
      "music": "text_to_audio",
      "extend": "text_to_audio",
      "cover": "text_to_audio"
    }
  },
  "suno-sfx-v5.5": {
    "defaultModeId": "sfx",
    "modes": {
      "sfx": "text_to_audio"
    }
  },
  "lyria-3.5": {
    "defaultModeId": "music",
    "modes": {
      "music": "text_to_audio"
    }
  },
  "volcengine-doubao-tts": {
    "defaultModeId": "speech",
    "modes": {
      "speech": "text_to_audio"
    }
  },
  "seed-tts": {
    "defaultModeId": "speech",
    "modes": {
      "speech": "text_to_audio"
    }
  },
  "modelscope-image": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image"
    }
  },
  "modelscope-image-edit": {
    "defaultModeId": "edit",
    "modes": {
      "edit": "image_edit"
    }
  },
  "volcengine-seedream": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "volcengine-seedream-5-pro": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "dreamina-image": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "i2i": "image_edit"
    }
  },
  "dreamina-upscale": {
    "defaultModeId": "upscale",
    "modes": {
      "upscale": "image_edit"
    }
  },
  "codex-imagegen": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "i2i": "image_edit"
    }
  },
  "antigravity-image": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "i2i": "image_edit"
    }
  },
  "hunyuan3d": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_3d",
      "image": "image_to_3d"
    }
  },
  "hitem3d": {
    "defaultModeId": "image",
    "modes": {
      "image": "image_to_3d"
    }
  },
  "meshy6": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_3d",
      "image": "image_to_3d"
    }
  },
  "rh-seedream-4.5": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_image",
      "edit": "image_edit"
    }
  },
  "rh-nano-banana": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_image",
      "edit": "image_edit"
    }
  },
  "rh-gpt-image-2": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_image",
      "edit": "image_edit"
    }
  },
  "rh-qwen-image-2.0": {
    "defaultModeId": "text",
    "modes": {
      "text": "text_to_image",
      "edit": "image_edit"
    }
  },
  "agnes-image": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  },
  "agnes-image-2.1": {
    "defaultModeId": "t2i",
    "modes": {
      "t2i": "text_to_image",
      "edit": "image_edit"
    }
  }
};
