// @generated by scripts/gen-archetype-wire-defaults.ts — 请勿手改（改档案后跑 pnpm gen:archetype-defaults）。
// 档案参数默认值桥接（audio 分片）。合并出口在 archetypeWireDefaults.generated.ts。
export const ARCHETYPE_WIRE_DEFAULTS_AUDIO: Record<string, Record<string, Record<string, Record<string, unknown>>>> = {
  "minimax-music-3": {
    "text_to_audio": {
      "*": {
        "duration": 30
      }
    }
  },
  "minimax-speech-2.8": {
    "text_to_audio": {
      "*": {
        "voice_id": "English_expressive_narrator",
        "speed": 1,
        "volume": 1,
        "pitch": 0,
        "language_boost": "auto"
      }
    }
  },
  "eleven-v3": {
    "text_to_audio": {
      "*": {
        "voice_id": "JBFqnCBsd6RMkjVDRZzb",
        "language_code": "",
        "stability": 0.5,
        "similarity_boost": 0.75,
        "style": 0,
        "speed": 1,
        "use_speaker_boost": true
      },
      "runway": {
        "voice_preset_id": "Maya",
        "stability": 0.5,
        "similarity_boost": 0.75,
        "style": 0,
        "speed": 1,
        "use_speaker_boost": true,
        "language_code": "",
        "apply_text_normalization": "auto"
      }
    }
  },
  "eleven-multilingual-v2": {
    "text_to_audio": {
      "*": {
        "voice_preset_id": "Maya",
        "model": "eleven_multilingual_v2"
      }
    }
  },
  "eleven-music-v2": {
    "text_to_audio": {
      "*": {
        "duration_seconds": 30,
        "force_instrumental": false
      }
    }
  },
  "eleven-sfx-v2": {
    "text_to_audio": {
      "*": {
        "duration_seconds": 5,
        "loop": false,
        "prompt_influence": 0.3
      },
      "runway": {
        "duration_seconds": 5,
        "loop": false
      }
    }
  },
  "eleven-scribe-v2": {
    "transcribe": {
      "*": {
        "language_code": "",
        "diarize": true,
        "tag_audio_events": true,
        "timestamps_granularity": "word"
      }
    }
  },
  "runway-seed-audio": {
    "text_to_audio": {
      "*": {
        "output_format": "mp3",
        "sample_rate": 44100,
        "speech_rate": 0,
        "loudness_rate": 0,
        "pitch_rate": 0,
        "model": "seed_audio"
      }
    }
  },
  "nomi-audio": {
    "text_to_audio": {
      "*": {
        "voice": "alloy",
        "speed": 1,
        "model": "gpt-4o-mini-tts"
      }
    },
    "transcribe": {
      "*": {
        "language": "",
        "model": "whisper-1"
      }
    }
  },
  "suno-v5.5": {
    "text_to_audio": {
      "*": {
        "callBackUrl": "https://nomiaqm.com/api/vendor-callbacks/kie/suno/ack",
        "instrumental": false,
        "customMode": false,
        "duration": 30
      }
    }
  },
  "suno-sfx-v5.5": {
    "text_to_audio": {
      "*": {
        "sound_type": "one-shot"
      }
    }
  },
  "lyria-3.5": {
    "text_to_audio": {
      "*": {
        "length": 60
      }
    }
  },
  "volcengine-doubao-tts": {
    "text_to_audio": {
      "*": {
        "voice": "zh_female_vv_uranus_bigtts"
      }
    }
  },
  "seed-tts": {
    "text_to_audio": {
      "*": {
        "voice": "zh_female_vv_uranus_bigtts"
      }
    }
  }
};
