import React from 'react'
import { AgentPanelV4Panel, type AgentPanelV4View } from '../../workbench/ai/v4/AgentPanelV4Panel'
import type { LabState } from './agentPanelKit'

const entry = (id: string, name: string, view: AgentPanelV4View, source = '2026-09-06-agent-panel-v4.md'): LabState => ({ id, name, source, coverage: 'shell', render: () => <AgentPanelV4Panel view={view} /> })

export const AGENT_PANEL_V4_STATES: readonly LabState[] = [
  entry('v4-main', 'Main · 一页读懂', 'main'),
  entry('v4-feasible', 'Feasible · 可行性', 'feasible'),
  entry('v4-vocabulary-user', 'Vocabulary · 用户气泡（附件）', 'vocabulary-user'),
  entry('v4-vocabulary-assistant-streaming', 'Vocabulary · 助手文本（流式）', 'process'),
  entry('v4-vocabulary-tool-running', 'Vocabulary · 收据（进行中）', 'rendering'),
  entry('v4-vocabulary-tool-failed', 'Vocabulary · 收据（失败）', 'sources'),
  entry('v4-vocabulary-task-complete', 'Vocabulary · 任务卡（多选完成）', 'main'),
  entry('v4-vocabulary-intervention', 'Vocabulary · 介入槽（确认/不要）', 'main'),
  entry('v4-vocabulary-queue', 'Vocabulary · 队列行', 'process'),
  entry('v4-vocabulary-context', 'Vocabulary · Context 环与展开', 'main'),
  entry('v4-composer-idle', 'Composer · 空闲一行', 'composer'),
  entry('v4-composer-running', 'Composer · 运行中', 'process'),
  entry('v4-composer-reference', 'Composer · 带引用', 'sources'),
  entry('v4-composer-model-popover', 'Composer · 模型弹层', 'model-popover'),
  entry('v4-composer-permission-step', 'Composer · 权限每步问', 'permission-step'),
  entry('v4-composer-permission-safe-auto', 'Composer · 权限自动改', 'composer'),
  entry('v4-composer-permission-project', 'Composer · 权限全自动', 'permission-project'),
  entry('v4-composer-skill-popover', 'Composer · Skill 弹层', 'skill-popover'),
  entry('v4-composer-height-84', 'Composer · 高度① 初始一行', 'composer'),
  entry('v4-composer-height-30', 'Composer · 高度② 自动增长', 'height-growth'),
  entry('v4-composer-height-scroll', 'Composer · 高度③ 封顶滚动', 'height-scroll'),
  entry('v4-process-flow', 'Process · 7 时刻 flow', 'process'),
  entry('v4-rendering', 'Rendering · 生成中', 'rendering'),
  entry('v4-sources', 'Sources · 引用与附件', 'sources'),
  entry('v4-flow-creation', 'FlowCreation · 创作流程', 'flow-creation'),
  entry('v4-flow-generation', 'FlowGeneration · 生成流程', 'flow-generation'),
  entry('v4-flow-preview', 'FlowPreview · 预览流程', 'flow-preview'),
  entry('v4-collapsed', 'Collapsed · 收起坞 rail', 'collapsed'),
  entry('v4-dark', 'Dark · 暗色 token 翻转', 'dark'),
  entry('v4-tool-input-streaming', 'Vocabulary · 收据（input-streaming）', 'v4-tool-input-streaming'),
  entry('v4-tool-input-available', 'Vocabulary · 收据（input-available）', 'v4-tool-input-available'),
  entry('v4-tool-approval-requested', 'Vocabulary · 收据（approval-requested）', 'v4-tool-approval-requested'),
  entry('v4-tool-approval-responded', 'Vocabulary · 收据（approval-responded）', 'v4-tool-approval-responded'),
  entry('v4-tool-output-available', 'Vocabulary · 收据（output-available）', 'v4-tool-output-available'),
  entry('v4-tool-output-denied', 'Vocabulary · 收据（output-denied）', 'v4-tool-output-denied'),
  entry('v4-tool-output-error', 'Vocabulary · 收据（output-error）', 'v4-tool-output-error'),
  entry('v4-task-queued', 'Vocabulary · 任务卡（排队）', 'v4-task-queued'),
  entry('v4-task-failed', 'Vocabulary · 任务卡（失败）', 'v4-task-failed'),
  entry('v4-task-stopped', 'Vocabulary · 任务卡（已停止）', 'v4-task-stopped'),
  entry('v4-intervention-question', 'Vocabulary · 介入槽（反问）', 'v4-intervention-question'),
  entry('v4-intervention-plan', 'Vocabulary · 介入槽（计划）', 'v4-intervention-plan'),
  entry('v4-intervention-spend', 'Vocabulary · 介入槽（付费）', 'v4-intervention-spend'),
  entry('v4-intervention-credential', 'Vocabulary · 介入槽（缺凭证）', 'v4-intervention-credential'),
  entry('v4-intervention-deviation', 'Vocabulary · 介入槽（有出入）', 'v4-intervention-deviation'),

]
