export const zhGenerationCommon = {
  provenance: {
    dialogAria: '生成记录',
    title: '生成记录 · {{name}}',
    unavailable: '该节点没有可追溯的生成记录。',
    possibleReasons: '可能原因：',
    legacyReason: '节点来自 v0.4.0 之前的旧项目（生成记录是 v0.5 新增能力）',
    localReason: '素材为本地导入，非 AI 生成',
    failedReason: '生成调用失败，未写入生成记录',
    provider: '供应商',
    model: '模型',
    time: '时间',
    prompt: '提示词',
    empty: '（空）',
    copyPrompt: '复制提示词',
    negativePrompt: '负面提示词',
    params: '参数',
    requestId: '供应商请求 ID',
    regenerate: '用相同参数重生成',
  },
} as const

type TranslationShape<T> = {
  [K in keyof T]: T[K] extends string ? string : TranslationShape<T[K]>
}

export const enGenerationCommon = {
  provenance: {
    dialogAria: 'Generation record',
    title: 'Generation record · {{name}}',
    unavailable: 'No traceable generation record is available for this node.',
    possibleReasons: 'Possible reasons:',
    legacyReason: 'The node comes from a project older than v0.4.0 (generation records were added in v0.5)',
    localReason: 'The asset was imported locally rather than generated by AI',
    failedReason: 'The generation request failed before a record was saved',
    provider: 'Provider',
    model: 'Model',
    time: 'Time',
    prompt: 'Prompt',
    empty: '(Empty)',
    copyPrompt: 'Copy prompt',
    negativePrompt: 'Negative prompt',
    params: 'Parameters',
    requestId: 'Provider request ID',
    regenerate: 'Regenerate with same parameters',
  },
} satisfies TranslationShape<typeof zhGenerationCommon>
