/**
 * Model-access journey manifest.
 *
 * This is the test contract, not a vendor support list. Production unions remain the
 * source of truth; manifest.test.mjs reads those unions and checks that this matrix
 * covers every value. A journey only counts when level=roundtrip and it drives the
 * visible Electron UI through access, configuration, execution, and result/recovery.
 */

const covers = (value) => Object.freeze(value)

export const MODEL_ACCESS_JOURNEYS = Object.freeze([
  {
    id: 'J01',
    title: '中转站接入后生成图片和视频',
    statement: '我有一个 new-api 地址和 key，要从模型发现一直走到图片与视频产物。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/relay-roundtrip.walk.mjs',
    profiles: ['relay-sync-image', 'relay-async-video'],
    covers: covers({
      entries: ['relay-model-discovery', 'provider-adapter'],
      billingKinds: ['image', 'video'],
      taskKinds: ['text_to_image', 'image_edit', 'text_to_video', 'image_to_video'],
      auth: ['bearer'],
      providers: ['openai-compatible', 'declarative-http'],
      lifecycles: ['sync-json', 'create-poll'],
      ingestion: ['inline-base64', 'public-url'],
      slots: ['first_frame'],
      outputs: ['url', 'async-asset'],
      recoveries: [],
    }),
  },
  {
    id: 'J02',
    title: '已知供应商单 key 接入',
    statement: '我只有一个已知平台 key，要从供应商卡解锁并完成一张图。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/provider-protocols.walk.mjs',
    profiles: ['known-key-image'],
    covers: covers({
      entries: ['known-single-key'],
      billingKinds: ['image'],
      taskKinds: ['text_to_image'],
      auth: ['x-api-key'],
      providers: ['declarative-http'],
      lifecycles: ['sync-json'],
      ingestion: ['upload-multipart'],
      slots: ['mask'],
      outputs: ['base64'],
      recoveries: [],
    }),
  },
  {
    id: 'J03',
    title: '多段凭证配音',
    statement: '我有 App ID 和 Access Token，要从两个输入框接入并得到可播放声音。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/provider-protocols.walk.mjs',
    profiles: ['multi-credential-ndjson-audio'],
    covers: covers({
      entries: ['known-multi-credential'],
      billingKinds: ['audio'],
      taskKinds: ['text_to_audio', 'image_to_audio'],
      auth: ['multi-credential'],
      providers: ['declarative-http'],
      lifecycles: ['binary', 'ndjson'],
      ingestion: ['none'],
      slots: [],
      outputs: ['binary'],
      recoveries: [],
    }),
  },
  {
    id: 'J04',
    title: '三种文本协议可用',
    statement: '我有兼容服务，要通过预设/协议选择让对话、改写和看图描述都返回文本。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/provider-protocols.walk.mjs',
    profiles: ['openai-sse-text', 'responses-json-text', 'anthropic-image-to-prompt'],
    covers: covers({
      entries: ['official-provider-preset'],
      billingKinds: ['text'],
      taskKinds: ['chat', 'prompt_refine', 'image_to_prompt'],
      auth: ['bearer', 'x-api-key', 'query'],
      providers: ['openai-compatible', 'openai-responses', 'anthropic'],
      lifecycles: ['sync-json', 'sse'],
      ingestion: ['inline-base64'],
      slots: ['image_ref'],
      outputs: ['text'],
      recoveries: [],
    }),
  },
  {
    id: 'J05',
    title: '自动适配逐模式失败后继续',
    statement: '自动适配猜错一个模式时，我仍能接入其它模式并修好失败模式。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/relay-roundtrip.walk.mjs',
    profiles: ['adapter-mode-repair'],
    covers: covers({
      entries: ['provider-adapter'],
      billingKinds: ['image', 'video'],
      taskKinds: ['image_edit', 'image_to_video'],
      auth: ['bearer'],
      providers: ['declarative-http'],
      lifecycles: ['create-poll'],
      ingestion: ['upload-url'],
      slots: ['first_frame'],
      outputs: ['async-asset'],
      recoveries: ['request-shape'],
    }),
  },
  {
    id: 'J06',
    title: '无文档时用 curl 接 fal-like 队列',
    statement: '我只有 curl 和响应样例，要用自定义调用接入带上传和三段队列的 API。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/custom-call-fal.walk.mjs',
    profiles: ['fal-like-custom-queue'],
    covers: covers({
      entries: ['custom-call-script'],
      billingKinds: ['image', 'video'],
      taskKinds: ['image_edit', 'image_to_video'],
      auth: ['custom-header'],
      providers: ['custom-script'],
      lifecycles: ['create-status-result'],
      ingestion: ['upload-url', 'public-url'],
      slots: ['first_frame', 'last_frame'],
      outputs: ['url', 'async-asset'],
      recoveries: [],
    }),
  },
  {
    id: 'J07',
    title: '自定义脚本现场修复',
    statement: '脚本第一次字段写错时，我要看见实际请求和上游错误，修改后在原节点成功。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/custom-call-fal.walk.mjs',
    profiles: ['custom-call-repair'],
    covers: covers({
      entries: ['custom-call-script', 'failure-recovery'],
      billingKinds: ['video'],
      taskKinds: ['image_to_video'],
      auth: ['custom-header'],
      providers: ['custom-script'],
      lifecycles: ['create-status-result'],
      ingestion: ['upload-url'],
      slots: ['first_frame'],
      outputs: ['async-asset'],
      recoveries: ['request-shape', 'invalid-response', 'empty-output'],
    }),
  },
  {
    id: 'J08',
    title: 'ComfyUI 预设、导入和多实例',
    statement: '我本机有 ComfyUI，要从地址/工作流接入并在正确实例得到图片、视频和 3D。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/local-backends.walk.mjs',
    profiles: ['comfyui-workflow-video'],
    covers: covers({
      entries: ['comfyui-preset', 'comfyui-workflow-import', 'comfyui-multi-instance'],
      billingKinds: ['image', 'video', 'model3d'],
      taskKinds: ['text_to_image', 'image_edit', 'text_to_video', 'image_to_video', 'text_to_3d', 'image_to_3d'],
      auth: ['none'],
      providers: ['comfyui'],
      lifecycles: ['http-websocket'],
      ingestion: ['comfyui-upload'],
      slots: ['first_frame', 'video_ref'],
      outputs: ['url', 'async-asset'],
      recoveries: ['url'],
    }),
  },
  {
    id: 'J09',
    title: '即梦登录与参考模式',
    statement: '我有即梦会员，要登录后把单图、首尾帧、全能参考和多帧送进 CLI。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/local-backends.walk.mjs',
    profiles: ['dreamina-reference-process'],
    covers: covers({
      entries: ['dreamina-oauth'],
      billingKinds: ['image', 'video'],
      taskKinds: ['text_to_image', 'image_edit', 'text_to_video', 'image_to_video'],
      auth: ['oauth-session'],
      providers: ['process'],
      lifecycles: ['process'],
      ingestion: ['process-local-file'],
      slots: ['first_frame', 'last_frame', 'image_ref', 'video_ref', 'audio_ref'],
      outputs: ['local-file'],
      recoveries: ['auth'],
    }),
  },
  {
    id: 'J10',
    title: 'Codex 本地生图',
    statement: '我已登录 Codex，要在模型面板启用后从图片节点得到本地资产。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/local-backends.walk.mjs',
    profiles: ['codex-local-process'],
    covers: covers({
      entries: ['codex-local'],
      billingKinds: ['image'],
      taskKinds: ['text_to_image'],
      auth: ['none'],
      providers: ['process'],
      lifecycles: ['process'],
      ingestion: ['process-local-file'],
      slots: [],
      outputs: ['local-file'],
      recoveries: [],
    }),
  },
  {
    id: 'J11',
    title: '模型类型纠错后生成',
    statement: '自动分类错了时，我要在 UI 改成正确类型，无需重接入即可生成。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/relay-roundtrip.walk.mjs',
    profiles: ['manual-kind-repair'],
    covers: covers({
      entries: ['manual-model-retype'],
      billingKinds: ['image', 'video', 'audio', 'model3d'],
      taskKinds: ['text_to_image', 'text_to_video', 'text_to_audio', 'text_to_3d'],
      auth: ['bearer'],
      providers: ['declarative-http'],
      lifecycles: ['sync-json', 'create-poll'],
      ingestion: [],
      slots: [],
      outputs: ['url'],
      recoveries: ['model-kind'],
    }),
  },
  {
    id: 'J12',
    title: '接入与生成错误回诊',
    statement: 'URL、key 或任务失败时，我要按 UI 提示修好并在原节点重试成功。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/recovery-roundtrip.walk.mjs',
    profiles: ['auth-url-timeout-repair'],
    covers: covers({
      entries: ['failure-recovery'],
      billingKinds: ['image'],
      taskKinds: ['text_to_image'],
      auth: ['bearer'],
      providers: ['openai-compatible', 'declarative-http'],
      lifecycles: ['sync-json'],
      ingestion: ['none'],
      slots: [],
      outputs: ['url'],
      recoveries: ['auth', 'url', 'rate-limit', 'server', 'timeout', 'invalid-response', 'empty-output'],
    }),
  },
  {
    id: 'J13',
    title: '模型声明的全部参考槽',
    statement: '不同模型需要不同素材时，我要按 UI 模式连接素材并保持顺序与语义。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/reference-modes.walk.mjs',
    profiles: ['ordered-multimodal-wire'],
    covers: covers({
      entries: ['known-single-key', 'custom-call-script'],
      billingKinds: ['image', 'video', 'audio'],
      taskKinds: ['image_edit', 'image_to_video', 'image_to_audio'],
      auth: ['bearer'],
      providers: ['declarative-http'],
      lifecycles: ['multipart', 'create-poll'],
      ingestion: ['upload-stream', 'upload-multipart', 'anon-chain'],
      slots: ['first_frame', 'last_frame', 'image_ref', 'video_ref', 'audio_ref', 'source_video', 'mask'],
      outputs: ['url', 'async-asset'],
      recoveries: [],
      modeShapes: ['input-key', 'single-value', 'array-value', 'character-indexed', 'vendor-params', 'model-enum', 'combine-role-array', 'combine-flat-array', 'fixed-params', 'variant'],
    }),
  },
  {
    id: 'J14',
    title: '配音、转录和 3D 产物',
    statement: '我要在真实节点中得到声音、转录文本和 GLB，而不是只看到接口成功。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/media-3d-roundtrip.walk.mjs',
    profiles: ['transcribe-multipart-text', 'async-image-to-3d'],
    covers: covers({
      entries: ['known-single-key'],
      billingKinds: ['audio', 'model3d'],
      taskKinds: ['text_to_audio', 'transcribe', 'text_to_3d', 'image_to_3d'],
      auth: ['bearer'],
      providers: ['declarative-http'],
      lifecycles: ['binary', 'multipart', 'create-poll'],
      ingestion: ['upload-stream'],
      slots: ['first_frame', 'audio_ref'],
      outputs: ['text', 'binary', 'async-asset'],
      recoveries: [],
      modeShapes: [],
    }),
  },
  {
    id: 'J15',
    title: '最小材料探测与诚实降级',
    statement: '我只有 URL、key 和模型 ID，没有文档、curl 或文本脑；系统要用真实探测推进，不能猜成已可用。',
    mode: 'stable',
    level: 'roundtrip',
    script: 'tests/ux/model-access-journeys/minimal-material.walk.mjs',
    profiles: ['minimal-material-honest-stop'],
    covers: covers({
      entries: ['minimal-material-probe', 'relay-model-discovery', 'provider-adapter', 'custom-call-script'],
      billingKinds: ['image'],
      taskKinds: ['text_to_image'],
      auth: ['bearer'],
      providers: ['openai-compatible', 'declarative-http', 'custom-script'],
      lifecycles: ['sync-json'],
      ingestion: ['none'],
      slots: [],
      outputs: ['url'],
      recoveries: ['request-shape', 'invalid-response'],
      modeShapes: [],
    }),
  },
])

export const STABLE_ROUNDTRIP_JOURNEYS = Object.freeze(
  MODEL_ACCESS_JOURNEYS.filter((journey) => journey.mode === 'stable' && journey.level === 'roundtrip'),
)
